import {NextRequest,NextResponse} from 'next/server';
import {loadPilotReadModel} from '../../../lib/hepe/pilot-read';

type Mapping={plo_code:string;irm_level:string;verification_status:string};
type Snap={course_code:string;title_th:string;title_en:string;credit_value:number;credit_pattern:string;course_role:string;group_name_th:string;verification_status:string;mappings:Mapping[];description_th?:string;description_en?:string;description_status?:string;description_verification_status?:string;description_authority_status?:string};
const HED2503_DESCRIPTION_TH='พัฒนาการและเพศของวัยรุ่น ความหลากหลายทางเพศ บทบาทและสิทธิทางเพศ การป้องกันการตั้งครรภ์ การตั้งครรภ์ไม่พร้อม การยุติการตั้งครรภ์ โรคติดต่อทางเพศสัมพันธ์ เจตคติทางเพศ การให้คำปรึกษาทางเพศ การวัดและประเมินผลการสอนเพศวิถี';
const HED2503_DESCRIPTION_EN='Adolescent and gender development, gender diversity, gender roles and rights, pregnancy prevention, unplanned pregnancy, induced abortion, sexually transmitted diseases, sexual attitudes, sexual counseling, and Measurement and evaluation of sexuality education teaching in the classroom.';
const OUT_OF_AUTHORITY_PREFIXES=['RAM','EDU'];
const SNAPSHOT:Snap[]=[
 {course_code:'HED1501',title_th:'การสร้างเสริมสุขภาพส่วนบุคคล',title_en:'Personal Health Promotion',credit_value:3,credit_pattern:'3 (3-0-6)',course_role:'REQUIRED',group_name_th:'สุขศึกษา วิชาเอกบังคับ',verification_status:'VALIDATED',mappings:[{plo_code:'PLO3',irm_level:'I',verification_status:'SOURCE_VERIFIED'}]},
 {course_code:'HED2503',title_th:'เพศวิถีศึกษา',title_en:'Sexuality Education',credit_value:3,credit_pattern:'3 (3-0-6)',course_role:'REQUIRED',group_name_th:'สุขศึกษา วิชาเอกบังคับ',verification_status:'VALIDATED',mappings:[{plo_code:'PLO3',irm_level:'R',verification_status:'SOURCE_VERIFIED'}],description_th:HED2503_DESCRIPTION_TH,description_en:HED2503_DESCRIPTION_EN,description_status:'DRAFT',description_verification_status:'SOURCE_TEXT_CROSSCHECKED',description_authority_status:'WORKING_SOURCE_CANDIDATE'},
 {course_code:'HED2504',title_th:'การจัดการเรียนรู้สุขศึกษา',title_en:'Health Education Learning Management',credit_value:3,credit_pattern:'3 (2-2-5)',course_role:'REQUIRED',group_name_th:'สุขศึกษา วิชาเอกบังคับ',verification_status:'VALIDATED',mappings:[{plo_code:'PLO4',irm_level:'R',verification_status:'SOURCE_VERIFIED'}]},
 {course_code:'HED3502',title_th:'ยาและยาเสพติด',title_en:'Drugs and Substance Abuse',credit_value:3,credit_pattern:'3 (3-0-6)',course_role:'REQUIRED',group_name_th:'สุขศึกษา วิชาเอกบังคับ',verification_status:'VALIDATED',mappings:[{plo_code:'PLO3',irm_level:'M',verification_status:'SOURCE_VERIFIED'}]},
 {course_code:'HED3504',title_th:'การส่งเสริมสุขภาพจิต',title_en:'Mental Health Promotion',credit_value:3,credit_pattern:'3 (3-0-6)',course_role:'REQUIRED',group_name_th:'สุขศึกษา วิชาเอกบังคับ',verification_status:'VALIDATED',mappings:[{plo_code:'PLO3',irm_level:'M',verification_status:'SOURCE_VERIFIED'}]},
 {course_code:'HED3505',title_th:'โปรแกรมสุขภาพในโรงเรียนและการประเมินผล',title_en:'School Health Program and Evaluation',credit_value:3,credit_pattern:'3 (3-0-6)',course_role:'REQUIRED',group_name_th:'สุขศึกษา วิชาเอกบังคับ',verification_status:'VALIDATED',mappings:[{plo_code:'PLO3',irm_level:'M',verification_status:'SOURCE_VERIFIED'}]},
 {course_code:'PED1101',title_th:'ปรัชญาพลศึกษาและกีฬา',title_en:'Physical Education and Sport Philosophy',credit_value:3,credit_pattern:'3 (3-0-6)',course_role:'REQUIRED',group_name_th:'พลศึกษา วิชาเอกบังคับ',verification_status:'VALIDATED',mappings:[{plo_code:'PLO3',irm_level:'I',verification_status:'SOURCE_VERIFIED'}]},
 {course_code:'PED1501',title_th:'การสอนยิมนาสติก',title_en:'Gymnastic Instructions',credit_value:2,credit_pattern:'2 (1-2-3)',course_role:'REQUIRED',group_name_th:'พลศึกษา วิชาเอกบังคับ',verification_status:'VALIDATED',mappings:[{plo_code:'PLO3',irm_level:'I',verification_status:'SOURCE_VERIFIED'}]}
];
function authorityScope(courseCode:string){const prefix=OUT_OF_AUTHORITY_PREFIXES.find(p=>courseCode.toUpperCase().startsWith(p));return prefix?{state:'OUT_OF_AUTHORITY_SCOPE',prefix,advisoryProcessing:false,reason:'COURSE_GROUP_OUTSIDE_PROGRAMME_DECISION_AUTHORITY'}:{state:'IN_ADVISORY_AUTHORITY_SCOPE',prefix:null,advisoryProcessing:true,reason:null};}
function coverage(courseCode:string,hasDescription:boolean,mappings:Mapping[]){
 const scope=authorityScope(courseCode); const isPilot=courseCode==='HED2503';
 if(!scope.advisoryProcessing)return {authorityScope:scope,courseIdentity:{state:'AVAILABLE',source:'CONTROLLED_CURRICULUM'},governedContextComplete:false,advisoryContextState:'OUT_OF_AUTHORITY_SCOPE',advisoryRule:'Do not analyze, score, recommend, or create curriculum-change candidates for this course group'};
 return {authorityScope:scope,courseIdentity:{state:'AVAILABLE',source:'CONTROLLED_CURRICULUM'},courseDescription:{state:hasDescription?'AVAILABLE':'MISSING',source:hasDescription?'COURSE_DESCRIPTION_VERSIONS':null},coursePloIrm:{state:mappings.length?'AVAILABLE':'MISSING',source:mappings.length?'CONTROLLED_CURRICULUM_MAPPING':null},clo:{state:'MISSING_IN_GOVERNED_DB',candidateSource:isPilot?'DPE_AQMS_MasterData_Import_v4.0_Course_Owner_Review_Approval.xlsx':null,candidateStatus:isPilot?'DRAFT_HUMAN_REVIEW_UNVERIFIED':null},learningActivities:{state:'MISSING_IN_GOVERNED_DB',candidateSource:isPilot?'DPE_AQMS_MasterData_Import_v4.0_Course_Owner_Review_Approval.xlsx':null,candidateStatus:isPilot?'DRAFT_HUMAN_REVIEW_UNVERIFIED':null},assessments:{state:'MISSING_IN_GOVERNED_DB',candidateSource:isPilot?'DPE_AQMS_MasterData_Import_v4.0_Course_Owner_Review_Approval.xlsx':null,candidateStatus:isPilot?'DRAFT_HUMAN_REVIEW_UNVERIFIED':null},governedContextComplete:false,advisoryContextState:isPilot?'ADVISORY_READY_WITH_CLASSIFIED_CANDIDATE_CONTEXT':'INSUFFICIENT_CONTEXT_FOR_AI_ADVISORY',advisoryRule:isPilot?'AI may analyze gaps and produce recommendation candidates only; candidate inputs remain non-baseline':'Do not auto-generate recommendation without sufficient classified context'};
}
function advisoryLayer(courseCode:string){const scope=authorityScope(courseCode);if(!scope.advisoryProcessing)return {state:'OUT_OF_AUTHORITY_SCOPE',reason:scope.reason,currentBaselineEffect:'NONE',auditEvidenceStatus:'NOT_ADMITTED'};if(courseCode!=='HED2503')return {state:'NOT_GENERATED',reason:'NO_AUTHORIZED_OR_SUFFICIENT_COURSE_ADVISORY_CONTEXT'};return {state:'APPROVED_FOR_FUTURE_CURRICULUM_IMPROVEMENT_CONSIDERATION',recommendationSetId:'RECSET-HED2503-20260912-01',sourceArtifact:'docs/hepe-data-01c-hed2503-ai-curriculum-improvement-recommendation.md',dispositions:['ACCEPT_CANDIDATE','EDIT_CANDIDATE','REJECT_CANDIDATE','DEFER_CANDIDATE'],currentBaselineEffect:'NONE',auditEvidenceStatus:'NOT_ADMITTED',humanAuthorityRequired:true};}
function snapshotResponse(req:NextRequest){const code=req.nextUrl.searchParams.get('courseCode');const course=SNAPSHOT.find(c=>c.course_code===code)??SNAPSHOT.find(c=>c.course_code==='HED2503')??SNAPSHOT[0];return NextResponse.json({state:'READY',environment:'NON-PRODUCTION',readOnly:true,sourceMode:'VERIFIED_CONTROLLED_SNAPSHOT',snapshotScope:'UAT_SUBSET',snapshotVersion:'2026-09-12-DATA01G',programme:{programme_code:'25510071103503',title_th:'ศษ.บ. สุขศึกษาและพลศึกษา',version_code:'2567-SOURCEB-VALIDATION'},course:{...course,description_th:course.description_th??null,description_en:course.description_en??null,description_status:course.description_status??'CONTROLLED_DESCRIPTION_NOT_AVAILABLE',description_verification_status:course.description_verification_status??null,description_authority_status:course.description_authority_status??null},mappings:course.mappings,academicContextCoverage:coverage(course.course_code,Boolean(course.description_th),course.mappings),advisoryLayer:advisoryLayer(course.course_code),authorityPolicy:{excludedPrefixes:OUT_OF_AUTHORITY_PREFIXES,excludedState:'OUT_OF_AUTHORITY_SCOPE',excludedFromAdvisoryProcessing:true},courses:SNAPSHOT.map(c=>({course_code:c.course_code,title_th:c.title_th,title_en:c.title_en,credit_value:c.credit_value})),boundary:{canonicalWrite:false,aiAuthority:false,auditEvidenceAdmission:false,production:false,rlsChanged:false,schemaChangedByData01Dto01F:false}});}
export async function GET(req:NextRequest){const model=await loadPilotReadModel();if(model.state==='AUTH_REQUIRED')return snapshotResponse(req);if(model.state!=='READY')return NextResponse.json({state:model.state},{status:403});const code=req.nextUrl.searchParams.get('courseCode');const course=code?model.courses.find((c:any)=>String(c.course_code)===code):model.courses[0];if(!course)return NextResponse.json({state:'COURSE_NOT_FOUND'},{status:404});const mappings=model.mappings.filter((m:any)=>String(m.course_code)===String(course.course_code)).map((m:any)=>({plo_code:m.plo_code,irm_level:m.irm_level,verification_status:m.verification_status??null}));const hasDescription=Boolean(course.description_th);return NextResponse.json({state:'READY',environment:'NON-PRODUCTION',readOnly:true,sourceMode:'AUTHENTICATED_LIVE_READ_MODEL',programme:{programme_code:model.programme.programme_code,title_th:model.programme.title_th,version_code:model.version.version_code},course:{course_code:course.course_code,title_th:course.title_th,title_en:course.title_en,credit_value:course.credit_value,credit_pattern:course.credit_pattern,course_role:course.course_role,group_name_th:course.group_name_th,verification_status:course.verification_status??null,description_th:course.description_th??null,description_en:course.description_en??null,description_status:course.description_status_code??'CONTROLLED_DESCRIPTION_NOT_AVAILABLE',description_verification_status:course.description_verification_status??null,description_authority_status:course.description_authority_status??null},mappings,academicContextCoverage:coverage(String(course.course_code),hasDescription,mappings),advisoryLayer:advisoryLayer(String(course.course_code)),authorityPolicy:{excludedPrefixes:OUT_OF_AUTHORITY_PREFIXES,excludedState:'OUT_OF_AUTHORITY_SCOPE',excludedFromAdvisoryProcessing:true},courses:model.courses.map((c:any)=>({course_code:c.course_code,title_th:c.title_th,title_en:c.title_en,credit_value:c.credit_value,advisory_scope:authorityScope(String(c.course_code)).state})),boundary:{canonicalWrite:false,aiAuthority:false,auditEvidenceAdmission:false,production:false,rlsChanged:false,schemaChangedByData01Dto01F:false}});}
