"use client";
import {useMemo,useState} from "react";
import {PANYA_PERSON,PANYA_PUBLICATIONS} from "../../lib/publications/panya-fixture";
import {PHAKAMAS_CANDIDATE,PHAKAMAS_CANDIDATES} from "../../lib/publications/phakamas-candidate";
import {fiveYearWindow,summarize2570} from "../../lib/publications/council-2570";
const tile:React.CSSProperties={padding:16,border:"1px solid #d9e3ef",borderRadius:12,background:"#fff"};
const cell:React.CSSProperties={padding:10,borderBottom:"1px solid #e3eaf4",verticalAlign:"top"};
export default function Council2570(){
 const [date,setDate]=useState("");
 const [person,setPerson]=useState<"PANYA"|"PHAKAMAS">("PANYA");
 const personName=person==="PANYA"?PANYA_PERSON.name:PHAKAMAS_CANDIDATE.nameTh;
 const works=person==="PANYA"?PANYA_PUBLICATIONS:PHAKAMAS_CANDIDATES;
 const window=useMemo(()=>fiveYearWindow(date),[date]);
 const result=useMemo(()=>summarize2570(works,date,"UNCONFIRMED"),[date,person]);
 const candidates=window?works.map(p=>{const first=`${p.yearBE-543}-01-01`,last=`${p.yearBE-543}-12-31`;return {p,yearState:last<window.start||first>window.end?"นอกช่วงทั้งปี":first<window.start||last>window.end?"ปีคาบเกี่ยวขอบเขต — ต้องใช้วันที่เผยแพร่จริง":"ปีอยู่ในช่วง — ยังต้องตรวจวันและเกณฑ์"};}):[];
 return <main style={{maxWidth:1220,margin:"auto",padding:"24px 16px",fontFamily:"system-ui,sans-serif",color:"#19314f"}}>
 <a href="/faculty-publications">← ทะเบียนผลงาน</a>
 <header style={{background:"#edf5ff",padding:22,borderRadius:18,marginTop:14}}><span style={{background:"#fff0c2",borderRadius:20,padding:"5px 10px",fontSize:12,fontWeight:700}}>NON-PRODUCTION · PROPOSED 2570 · NO COUNCIL APPROVAL CLAIM</span><h1>หลักสูตรปรับปรุง พ.ศ. 2570 — ประเมินคุณสมบัติรายบุคคล</h1><p>นับย้อนหลัง 5 ปีโดยผูกกับวันที่สภามหาวิทยาลัยอนุมัติ และตรวจหลักฐานผลงานเป็นรายเรื่องก่อนให้ผลด้านผลงาน</p></header>
 <section style={{...tile,marginTop:16}}><h2>เลือกบุคคลเพื่อประเมิน</h2><label htmlFor="person-select">รายชื่อ</label><p><select id="person-select" value={person} onChange={e=>setPerson(e.target.value as "PANYA"|"PHAKAMAS")} style={{padding:12,border:"1px solid #9bb5d8",borderRadius:8,fontSize:16,maxWidth:"100%"}}><option value="PANYA">ผศ.ปัญญา พุดซ้อน — VERIFIED PERSON</option><option value="PHAKAMAS">ผกามาศ รัตนบุษย์ / Phakanas Ratanabuth — CANDIDATE</option></select></p>{person==="PHAKAMAS"?<p style={{background:"#fff4d8",padding:12,borderRadius:8}}><b>NEEDS IDENTITY RECONCILIATION:</b> ชื่อภาษาอังกฤษที่แจ้งใช้ค้นหาได้ แต่ยังไม่ผูกกับตัวตน canonical ใน Supabase อัตโนมัติ; รายการผลงานเป็นเพียง candidate และยังไม่ใช่ทะเบียนครบถ้วน</p>:<p>ข้อมูลบุคคลจากทะเบียน Supabase; รายการผลงานยังเป็นชุดข้อมูลตัวอย่างที่ต้องรับรองแยกต่างหาก</p>}</section>
 <section style={{...tile,marginTop:16}}><h2>1. วันที่สภาอนุมัติหลักสูตร</h2><label htmlFor="council-date">วันที่ในตัวอย่างจำลอง (ยังไม่ใช่วันอนุมัติจริง)</label><p><input id="council-date" type="date" value={date} min="2027-01-01" max="2027-12-31" onChange={e=>setDate(e.target.value)} style={{padding:12,border:"1px solid #9bb5d8",borderRadius:8,fontSize:16}}/></p><strong style={{color:"#aa6810"}}>สถานะ: UNCONFIRMED — ยังไม่มีมติสภาและเลขที่เอกสารยืนยัน</strong><p>ระบบจะไม่ยอมรับวันที่ที่ผู้ใช้ทดลองกรอกเป็นวันที่อนุมัติจริง และจะไม่เปลี่ยนผลรับรองบุคคลโดยอัตโนมัติ</p>{window?<p style={{background:"#f0f6ff",padding:12,borderRadius:8}}>ช่วงคำนวณตัวอย่าง: <b>{window.start} ถึง {window.end}</b> (ค.ศ.) · ใช้แบบวันถัดจากวันครบรอบย้อนหลังห้าปีถึงวันอ้างอิง; ต้องตรวจนิยามช่วงกับหน่วยงานก่อนใช้เป็นเกณฑ์ทางการ</p>:<p style={{color:"#667085"}}>ยังไม่กรอกวันที่ตัวอย่าง จึงไม่คำนวณช่วงย้อนหลังแบบรายวัน</p>}</section>
 <section style={{...tile,marginTop:16}}><h2>2. ตารางแยกปี</h2>{window?<div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr style={{background:"#e9f2ff"}}>{["ปี พ.ศ.","ปี ค.ศ.","จำนวนผลงานในทะเบียนตัวอย่าง","รายละเอียด"].map(x=><th key={x} style={cell}>{x}</th>)}</tr></thead><tbody>{window.years.map(y=><tr key={y}><td style={cell}>{y}</td><td style={cell}>{y-543}</td><td style={cell}>{works.filter(p=>p.yearBE===y).length}</td><td style={cell}>{works.filter(p=>p.yearBE===y).map(p=>p.title).join("; ")||"ยังไม่พบในทะเบียนตัวอย่าง ไม่ใช่ข้อยืนยันว่าไม่มีผลงาน"}</td></tr>)}</tbody></table></div>:<p>โปรดเลือกวันที่ตัวอย่างก่อนดูตารางปี โดยผลรายปีไม่อาจแทนการตรวจวันเผยแพร่จริง</p>}</section>
 <section style={{...tile,marginTop:16}}><h2>3. ผลรายบุคคล — {personName}</h2><p>{person==="PANYA"?"ยืนยันข้อมูลบุคคลจาก Supabase academic_people; ผลงานเป็นชุดตัวอย่างที่ยังไม่ได้รับรองให้นับ":"ข้อมูลบุคคลเป็นรายการรอตรวจตัวตน ชื่อผู้แต่งในเอกสารหลักสูตรยังไม่พิสูจน์การผูกกับบุคคล canonical; จำนวนผลงานยังไม่ครบถ้วน"}</p><div style={{display:"flex",gap:12,flexWrap:"wrap"}}><div style={tile}>รายการค้นพบ <h2>{works.length}</h2></div><div style={tile}>รับรองให้นับ <h2>{result.verified}</h2></div><div style={tile}>ผลการตรวจ <h3 style={{color:"#a45b00"}}>รอหลักฐานวันอนุมัติ</h3></div></div><p><b>ข้อจำกัด:</b> ยังไม่มีการยืนยันวันที่สภาอนุมัติและความครบถ้วนของทะเบียนผลงาน จึงไม่แสดงว่าอาจารย์ผ่านหรือไม่ผ่านคุณสมบัติหลักสูตร 2570</p><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:14}}><thead><tr style={{background:"#e9f2ff"}}>{["ปี","ผลงาน","ความสัมพันธ์กับช่วงตัวอย่าง","ผลทางการ","หลักฐานที่ยังต้องตรวจ"].map(x=><th key={x} style={cell}>{x}</th>)}</tr></thead><tbody>{works.map(p=><tr key={p.id}><td style={cell}>{p.yearBE}</td><td style={cell}>{p.title}<p style={{fontSize:12,color:"#667085"}}>{p.citation}</p></td><td style={cell}>{candidates.find(c=>c.p.id===p.id)?.yearState||"ยังไม่กำหนดวันที่"}</td><td style={cell}><b style={{color:"#a45b00"}}>PENDING EVIDENCE</b></td><td style={cell}>{p.notes}</td></tr>)}</tbody></table></div></section>
 <section style={{...tile,marginTop:16}}><h2>4. เงื่อนไขก่อนรับรองคุณสมบัติ</h2><ol><li>มติสภามหาวิทยาลัย: วันอนุมัติ เลขที่มติ และไฟล์หลักฐานที่ตรวจสอบได้</li><li>ทะเบียนผลงานรายบุคคลและชื่อผู้แต่งที่ตรวจสอบตรงกัน</li><li>วันเผยแพร่/วันตอบรับที่ใช้ได้จริงตามเกณฑ์ และหลักฐานฉบับเต็ม</li><li>ประเภทผลงาน สาขาที่เกี่ยวข้อง ความซ้ำซ้อน และกฎฉบับที่มีผลใช้</li><li>ผู้มีอำนาจตรวจทานและลงผล; ตรวจองค์ประกอบคุณวุฒิและตำแหน่งแยกจากส่วนผลงาน</li></ol><p style={{color:"#ae341e"}}><b>AI เป็นผู้ช่วยวิเคราะห์เท่านั้น</b> ไม่สามารถอนุมัติหลักสูตร ลงผลคุณสมบัติ หรือปรับข้อมูล canonical ด้วยการเลือกวันที่บนหน้านี้</p></section>
 <p><a href="https://www.ops.go.th/th/role/edu-standard/item/6942-2022-07-22-03-17-22">อ้างอิง: เกณฑ์มาตรฐานหลักสูตรระดับปริญญาตรี พ.ศ. 2565 ↗</a></p>
 </main>;
}
