import { loadPilotReadModel } from '../../lib/hepe/pilot-read';

export default async function CurriculumPage({searchParams}:{searchParams:Promise<{q?:string;group?:string}>}){
 const model=await loadPilotReadModel(); const sp=await searchParams;
 if(model.state!=='READY') return <main className="workspace"><div className="module-wrap"><a className="breadcrumb" href="/">← Academic Command Center</a><section className="hero"><div className="brand-kicker">HEPE · CONTROLLED PILOT · NON-PRODUCTION</div><h1>Curriculum Structure</h1><p>Authority-aware controlled curriculum read experience.</p></section><div className="pill">{model.state}</div><div className="firewall">NON-PRODUCTION · NOT ACTIVE · NOT PUBLISHED</div></div></main>;
 const q=(sp.q??'').trim().toLowerCase(), group=sp.group??'';
 const filtered=model.courses.filter((c:any)=>(!q||String(c.course_code??'').toLowerCase().includes(q)||String(c.title_th??'').toLowerCase().includes(q)||String(c.title_en??'').toLowerCase().includes(q))&&(!group||c.group_code===group));
 const groups=[...new Map(model.courses.filter((c:any)=>c.group_code).map((c:any)=>[c.group_code,{code:c.group_code,name:c.group_name_th}])).values()] as any[];
 return <main className="workspace"><div className="module-wrap"><a className="breadcrumb" href="/">← Academic Command Center</a><section className="hero"><div className="brand-kicker">HEPE · BED-HEPE · CONTROLLED PILOT · NON-PRODUCTION</div><h1>Curriculum Structure</h1><p>Read-only Source-B-bound course registry. Missing values remain explicit; no course, title, group membership or credit semantics are inferred.</p></section><div className="pill">92 CONTROLLED COURSES · READ ONLY · NOT ACTIVE · NOT PUBLISHED</div>
 <form className="filterbar" method="get"><label>Search course <input name="q" defaultValue={sp.q??''} placeholder="Course code / Thai / English title"/></label><label>Course group <select name="group" defaultValue={group}><option value="">All groups</option>{groups.map((g:any)=><option key={g.code} value={g.code}>{g.code} · {g.name}</option>)}</select></label><button type="submit">Apply</button></form>
 <div className="table-wrap"><table><thead><tr><th>Code</th><th>Thai title</th><th>English title</th><th>Credits</th><th>Group</th><th>Source / verification</th></tr></thead><tbody>{filtered.map((c:any)=><tr key={c.curriculum_course_id}><td><strong>{c.course_code}</strong></td><td>{c.title_th||'NOT PROVIDED'}</td><td>{c.title_en||'NOT PROVIDED'}</td><td>{c.credit_pattern||String(c.credit_value??'NOT PROVIDED')}</td><td>{c.group_code?`${c.group_code} · ${c.group_name_th??'NOT PROVIDED'}`:'NOT PROVIDED'}</td><td>{c.source_page?`p.${c.source_page}`:'PROVENANCE NOT AVAILABLE'}<br/><span className="note">{c.verification_status??'UNVERIFIED'}</span></td></tr>)}</tbody></table></div>
 <div className="firewall">Showing {filtered.length} of 92 controlled courses · Programme 25510071103503 · Version 2567-SOURCEB-VALIDATION · No canonical write controls exposed.</div></div></main>
}
