'use client';
import {useEffect,useMemo,useState} from 'react';

type Course={course_code:string;title_th:string|null;title_en:string|null;credit_value:number|null};
type Clo={id:string,text:string,status:'DRAFT'|'ACCEPTED'};
type Context={state:string;course:any;courses:Course[];mappings:{plo_code:string|null;irm_level:string|null}[]};
const steps=['ข้อมูลรายวิชา','CLO / PLO','แผนการสอน','การประเมิน','ตรวจความครบถ้วน','ส่งตรวจ'];

export default function Tqf3Workspace(){
 const [step,setStep]=useState(0),[ctx,setCtx]=useState<Context|null>(null),[loading,setLoading]=useState(true),[courseCode,setCourseCode]=useState('');
 const [clos,setClos]=useState<Clo[]>([{id:'clo-1',text:'',status:'DRAFT'}]);
 const [week,setWeek]=useState(''),[assessment,setAssessment]=useState(''),[saved,setSaved]=useState(false),[aiNote,setAiNote]=useState('');
 async function load(code?:string){setLoading(true);try{const q=code?`?courseCode=${encodeURIComponent(code)}`:'';const r=await fetch(`/api/pilot-course-context${q}`,{cache:'no-store'});const j=await r.json();setCtx(j);if(j.course?.course_code)setCourseCode(j.course.course_code)}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 const accepted=clos.filter(c=>c.status==='ACCEPTED'&&c.text.trim()).length;
 const completion=useMemo(()=>[ctx?.course?.course_code,accepted>0?'yes':'',week,assessment].filter(Boolean).length*25,[ctx,accepted,week,assessment]);
 function updateClo(id:string,text:string){setClos(v=>v.map(c=>c.id===id?{...c,text,status:'DRAFT'}:c));setSaved(false)}
 function addClo(){setClos(v=>[...v,{id:`clo-${Date.now()}`,text:'',status:'DRAFT'}])}
 function removeClo(id:string){setClos(v=>v.length===1?v:v.filter(c=>c.id!==id))}
 function acceptClo(id:string){setClos(v=>v.map(c=>c.id===id&&c.text.trim()?{...c,status:'ACCEPTED'}:c))}
 function askAi(){
  if(!ctx?.course?.description_th){setAiNote('AI ยังไม่สร้างข้อเสนอ CLO เพราะฐานข้อมูล controlled ปัจจุบันยังไม่มีคำอธิบายรายวิชา ระบบจึงหยุดแบบ fail-closed เพื่อไม่สร้างผลลัพธ์จากข้อมูลไม่ครบ');return}
  setAiNote('AI advisory runtime ยังไม่ถูกเชื่อมใน Controlled Pilot นี้');
 }
 function saveDemo(){try{localStorage.setItem('hepe-tqf3-demo',JSON.stringify({courseCode,clos,week,assessment,savedAt:new Date().toISOString()}));}catch{}setSaved(true)}
 const next=()=>setStep(s=>Math.min(5,s+1)),back=()=>setStep(s=>Math.max(0,s-1));
 return <main className="guided-page"><header className="guided-header"><a href="/" className="back-home">← กลับงานของฉัน</a><div><div className="eyebrow">HEPE-UAT-UX-02 · มคอ.3</div><h1>จัดทำ มคอ.3</h1><p>ข้อมูลรายวิชาจากฐานข้อมูล + CLO Builder หลายข้อ + Human-controlled AI advisory</p></div><div className="progress-box"><strong>{completion}%</strong><span>DEMO workflow completion</span></div></header>
 <div className="notice"><strong>NON-PRODUCTION / READ-ONLY COURSE CONTEXT</strong> ข้อมูลรายวิชาอ่านจาก controlled database; CLO และข้อมูลที่ทดลองแก้ไขเก็บเฉพาะ browser ไม่มี canonical write และไม่เข้าสู่ Audit Evidence โดยอัตโนมัติ</div>
 <nav className="stepper">{steps.map((s,i)=><button key={s} className={i===step?'current':i<step?'done':''} onClick={()=>setStep(i)}><span>{i<step?'✓':i+1}</span><b>{s}</b></button>)}</nav>
 <section className="guided-card"><div className="guided-title"><div><div className="eyebrow">ขั้นตอน {step+1} จาก 6</div><h2>{steps[step]}</h2></div><span className="demo-badge">CONTROLLED PILOT</span></div>
 {step===0&&<>{loading?<p className="help-text">กำลังอ่านทะเบียนรายวิชาจากฐานข้อมูล...</p>:ctx?.state==='READY'?<><p className="help-text">เลือกรายวิชา ระบบจะดึงข้อมูลทะเบียนที่มีอยู่โดยอัตโนมัติ ไม่ต้องพิมพ์ชื่อวิชาและหน่วยกิตซ้ำ</p><label className="field">เลือกรายวิชา<select value={courseCode} onChange={e=>load(e.target.value)}>{ctx.courses.map(c=><option key={c.course_code} value={c.course_code}>{c.course_code} · {c.title_th||c.title_en}</option>)}</select></label><div className="db-context"><div><span>รหัสวิชา</span><strong>{ctx.course.course_code}</strong></div><div><span>ชื่อวิชา</span><strong>{ctx.course.title_th||'—'}</strong></div><div><span>หน่วยกิต</span><strong>{ctx.course.credit_pattern||ctx.course.credit_value||'—'}</strong></div><div><span>กลุ่มวิชา</span><strong>{ctx.course.group_name_th||'—'}</strong></div></div><div className="description-box"><div><strong>คำอธิบายรายวิชา</strong><span className="source-badge">DATABASE</span></div>{ctx.course.description_th?<p>{ctx.course.description_th}</p>:<p className="missing-data">ยังไม่มี controlled course description ในฐานข้อมูลปัจจุบัน — ระบบไม่สร้างข้อความทดแทนเอง</p>}</div></>:<div className="firewall">ไม่สามารถอ่าน controlled course context ได้: {ctx?.state||'UNKNOWN'}</div>}</>}
 {step===1&&<><p className="help-text">CLO สามารถมีได้หลายข้อ เพิ่ม/แก้ไข/ลบได้ทีละข้อ และต้องให้ผู้ใช้ยืนยันก่อนนำไปใช้ต่อใน workflow</p><div className="ai-advisory"><div><div className="eyebrow">AI ADVISORY · HUMAN CONTROLLED</div><h3>ให้ AI ช่วยเสนอ CLO</h3><p>AI ควรวิเคราะห์คำอธิบายรายวิชา + PLO + course context แล้วเสนอเป็นตัวเลือกเท่านั้น ผู้ใช้เป็นผู้ยอมรับ แก้ไข หรือลบทุกข้อ</p></div><button onClick={askAi}>วิเคราะห์และเสนอ CLO ด้วย AI</button></div>{aiNote&&<div className="ai-note">{aiNote}</div>}<div className="clo-list">{clos.map((c,i)=><article className="clo-card" key={c.id}><div className="clo-head"><strong>CLO{i+1}</strong><span className={c.status==='ACCEPTED'?'clo-status accepted':'clo-status'}>{c.status==='ACCEPTED'?'ผู้ใช้ยืนยันแล้ว':'รอผู้ใช้ตัดสินใจ'}</span></div><textarea rows={3} value={c.text} placeholder={`เขียน CLO${i+1} หรือรอ AI proposal เมื่อมี controlled course description`} onChange={e=>updateClo(c.id,e.target.value)}/><div className="clo-actions"><button onClick={()=>acceptClo(c.id)} disabled={!c.text.trim()}>✓ ยอมรับ</button><button onClick={()=>removeClo(c.id)} disabled={clos.length===1}>ลบ</button></div></article>)}</div><button className="add-clo" onClick={addClo}>＋ เพิ่ม CLO ด้วยตนเอง</button><div className="mapping-preview"><strong>PLO ที่มี mapping อยู่ใน controlled curriculum</strong>{ctx?.mappings?.length?<div>{ctx.mappings.map((m,i)=><span key={i}>{m.plo_code||'PLO?'} · {m.irm_level||'—'}</span>)}</div>:<p>ยังไม่พบ controlled course→PLO mapping สำหรับรายวิชานี้</p>}<small>รายการนี้เป็นบริบทประกอบการตัดสินใจ ไม่ใช่การยืนยัน CLO→PLO mapping ใหม่</small></div></>}
 {step===2&&<><p className="help-text">กำหนดกิจกรรมการเรียนรู้ หลังจากเลือก CLO ที่ผู้ใช้ยืนยันแล้ว</p><label className="field">กิจกรรมการเรียนรู้สัปดาห์ที่ 1<textarea rows={4} value={week} onChange={e=>{setWeek(e.target.value);setSaved(false)}}/></label><div className="helper-panel"><strong>CLO ที่ยืนยันแล้ว</strong><p>{accepted?clos.filter(c=>c.status==='ACCEPTED').map((c,i)=>`CLO${i+1}: ${c.text}`).join(' · '):'ยังไม่มี CLO ที่ผู้ใช้ยืนยัน'}</p></div></>}
 {step===3&&<><p className="help-text">ระบุวิธีประเมินที่ใช้ตรวจการบรรลุ CLO</p><label className="field">วิธีประเมิน<textarea rows={3} value={assessment} onChange={e=>{setAssessment(e.target.value);setSaved(false)}}/></label></>}
 {step===4&&<><p className="help-text">ตรวจความครบถ้วนของ DEMO draft ก่อน handoff</p><div className="review-list"><div><span>รายวิชาจาก controlled database</span><b>{ctx?.course?.course_code?'พร้อมตรวจ':'ยังขาดข้อมูล'}</b></div><div><span>CLO ที่ Human ยืนยัน</span><b>{accepted>0?`${accepted} ข้อ`:'ยังไม่มี'}</b></div><div><span>แผนการสอน</span><b>{week.trim()?'พร้อมตรวจ':'ยังขาดข้อมูล'}</b></div><div><span>การประเมิน</span><b>{assessment.trim()?'พร้อมตรวจ':'ยังขาดข้อมูล'}</b></div></div><p className="note">“พร้อมตรวจ” ไม่เท่ากับ PASS และไม่ใช่ Audit Evidence</p></>}
 {step===5&&<div className="handoff"><h3>DEMO draft พร้อมสำหรับ UAT handoff</h3><p>Canonical write, publication, activation และ AI approval ยังคงปิดทั้งหมด ผู้มีอำนาจทางวิชาการเป็นผู้ตัดสินใจเมื่อมี controlled workflow จริง</p><a className="primary-action" href="/tqf5">ดูขั้นถัดไป: มคอ.5 →</a></div>}
 <div className="guided-actions"><button onClick={back} disabled={step===0}>← ย้อนกลับ</button><div><button className="secondary" onClick={saveDemo}>บันทึก DEMO</button>{step<5&&<button className="primary" onClick={next}>ถัดไป →</button>}</div></div><div className="save-state">{saved?'บันทึก DEMO ใน browser แล้ว':'ยังไม่ได้บันทึก DEMO'}</div></section>
 <footer className="guided-footer">CANONICAL WRITE DISABLED · AI ADVISORY ONLY · HUMAN AUTHORITY PRESERVED · PRODUCTION NOT TOUCHED · AUDIT EVIDENCE ADMISSION DISABLED</footer></main>}
