'use client';
import {useMemo,useState} from 'react';
const steps=['ข้อมูลรายวิชา','CLO / PLO','แผนการสอน','การประเมิน','ตรวจความครบถ้วน','ส่งตรวจ'];
export default function Tqf3Workspace(){
 const [step,setStep]=useState(0);const [title,setTitle]=useState('รายวิชาตัวอย่างสำหรับทดลองกรอก มคอ.3');const [clo,setClo]=useState('ผู้เรียนสามารถอธิบายและประยุกต์สาระสำคัญของรายวิชาได้อย่างเหมาะสม');const [week,setWeek]=useState('อภิปรายกรณีศึกษาและกิจกรรมกลุ่ม');const [assessment,setAssessment]=useState('งานวิเคราะห์กรณีศึกษา');const [saved,setSaved]=useState(false);
 const completion=useMemo(()=>[title,clo,week,assessment].filter(v=>v.trim()).length*25,[title,clo,week,assessment]);
 function saveDemo(){try{localStorage.setItem('hepe-tqf3-demo',JSON.stringify({title,clo,week,assessment,savedAt:new Date().toISOString()}));}catch{}setSaved(true)}
 const next=()=>setStep(s=>Math.min(5,s+1)),back=()=>setStep(s=>Math.max(0,s-1));
 return <main className="guided-page"><header className="guided-header"><a href="/" className="back-home">← กลับงานของฉัน</a><div><div className="eyebrow">มคอ.3 · COURSE SPECIFICATION</div><h1>จัดทำ มคอ.3</h1><p>ทำทีละขั้น ระบบจะแจ้งว่าตอนนี้อยู่ตรงไหนและต้องทำอะไรต่อ</p></div><div className="progress-box"><strong>{completion}%</strong><span>ข้อมูล DEMO ที่กรอกแล้ว</span></div></header>
 <div className="notice"><strong>รุ่นทดลอง · NON-PRODUCTION</strong> ข้อมูลที่กรอกหน้านี้เก็บเฉพาะใน browser ไม่เขียนลงฐานข้อมูลหลักสูตรจริง และไม่ถือเป็น Audit Evidence</div>
 <nav className="stepper" aria-label="ขั้นตอนจัดทำ มคอ.3">{steps.map((s,i)=><button key={s} className={i===step?'current':i<step?'done':''} onClick={()=>setStep(i)}><span>{i<step?'✓':i+1}</span><b>{s}</b></button>)}</nav>
 <section className="guided-card"><div className="guided-title"><div><div className="eyebrow">ขั้นตอน {step+1} จาก 6</div><h2>{steps[step]}</h2></div><span className="demo-badge">DEMO</span></div>
 {step===0&&<><p className="help-text">ตรวจสอบหลักสูตรและระบุรายวิชาที่กำลังจัดทำ มคอ.3</p><div className="form-grid"><label>หลักสูตร<input value="ศษ.บ. สุขศึกษาและพลศึกษา" readOnly/></label><label>ฉบับหลักสูตร<input value="2567-SOURCEB-VALIDATION" readOnly/></label><label>ชื่อรายวิชาสำหรับทดลอง<input value={title} onChange={e=>{setTitle(e.target.value);setSaved(false)}}/></label><label>สถานะ<input value="DEMO DRAFT" readOnly/></label></div></>}
 {step===1&&<><p className="help-text">เขียนผลลัพธ์การเรียนรู้ของรายวิชา จากนั้นจึงตรวจความเชื่อมโยงกับ PLO</p><label className="field">ผลลัพธ์การเรียนรู้ (CLO)<textarea rows={5} value={clo} onChange={e=>{setClo(e.target.value);setSaved(false)}}/></label><div className="helper-panel"><strong>ระบบจริงจะช่วยอะไร?</strong><p>แสดง PLO ที่เกี่ยวข้องและช่วยตรวจความสอดคล้อง โดยการตัดสินใจ mapping ยังคงเป็นอำนาจของผู้รับผิดชอบทางวิชาการ</p><a href="/traceability">ดู PLO ของหลักสูตร →</a></div></>}
 {step===2&&<><p className="help-text">กำหนดหัวข้อและกิจกรรมการเรียนรู้ ตัวอย่างนี้ใช้เพียงสัปดาห์แรกเพื่อทดลอง UX</p><label className="field">กิจกรรมการเรียนรู้สัปดาห์ที่ 1<textarea rows={4} value={week} onChange={e=>{setWeek(e.target.value);setSaved(false)}}/></label><div className="helper-panel"><strong>เชื่อมกับ CLO</strong><p>DEMO-CLO-01 · ยังไม่มี canonical relationship ถูกสร้างจากข้อมูลทดลองนี้</p></div></>}
 {step===3&&<><p className="help-text">ระบุวิธีประเมินที่ใช้ตรวจว่าผู้เรียนบรรลุ CLO หรือไม่</p><div className="form-grid"><label>วิธีประเมิน<input value={assessment} onChange={e=>{setAssessment(e.target.value);setSaved(false)}}/></label><label>น้ำหนักตัวอย่าง (%)<input value="20" readOnly/></label></div><div className="helper-panel"><strong>หลักคิด</strong><p>กิจกรรมการประเมินควรสัมพันธ์กับ CLO และมีหลักฐานที่สามารถตรวจสอบย้อนหลังได้</p></div></>}
 {step===4&&<><p className="help-text">ตรวจสิ่งที่กรอกก่อนส่งต่อ ขั้นนี้ยังเป็นการตรวจ DEMO ไม่ใช่ QA verdict</p><div className="review-list"><div><span>ข้อมูลรายวิชา</span><b>{title.trim()?'พร้อมตรวจ':'ยังขาดข้อมูล'}</b></div><div><span>CLO</span><b>{clo.trim()?'พร้อมตรวจ':'ยังขาดข้อมูล'}</b></div><div><span>แผนการสอน</span><b>{week.trim()?'พร้อมตรวจ':'ยังขาดข้อมูล'}</b></div><div><span>การประเมิน</span><b>{assessment.trim()?'พร้อมตรวจ':'ยังขาดข้อมูล'}</b></div></div><p className="note">คำว่า “พร้อมตรวจ” หมายถึงมี DEMO input เท่านั้น ไม่ใช่ PASS และไม่ใช่ Audit Evidence</p></>}
 {step===5&&<><p className="help-text">ใน Controlled Pilot นี้ยังไม่ส่งอนุมัติจริง หน้านี้แสดง handoff ที่ระบบจริงจะใช้</p><div className="handoff"><h3>มคอ.3 พร้อมสำหรับการทดลองขั้นถัดไป</h3><p>เมื่อเปิดใช้ controlled record workflow ระบบจะส่งให้ผู้มีอำนาจตรวจตามบทบาท โดย AI ไม่มีสิทธิ์อนุมัติแทนบุคคล</p><a className="primary-action" href="/tqf5">ไปดูขั้นถัดไป: มคอ.5 →</a></div></>}
 <div className="guided-actions"><button onClick={back} disabled={step===0}>← ย้อนกลับ</button><div><button className="secondary" onClick={saveDemo}>บันทึก DEMO</button>{step<5&&<button className="primary" onClick={next}>ถัดไป →</button>}</div></div><div className="save-state">{saved?'บันทึก DEMO ใน browser แล้ว':'ยังไม่ได้บันทึก DEMO'}</div></section>
 <footer className="guided-footer">SAVE TARGET = LOCAL BROWSER ONLY · CANONICAL WRITE DISABLED · ACTIVATION/PUBLICATION/AUDIT EVIDENCE ADMISSION DISABLED</footer></main>}
