'use client';
import {useEffect,useMemo,useState} from 'react';

type Course={course_code:string;title_th:string|null;title_en:string|null;credit_value:number|null};
type Clo={id:string;text:string;status:'DRAFT'|'ACCEPTED'};
type WeekPlan={id:string;weekNo:number;topic:string;llo:string;cloLinks:string;activeLearning:string;assessmentActivity:string;rubric:string;evidence:string};
type AssessmentItem={id:string;name:string;weight:number;cloLinks:string;method:string;rubric:string};
type Context={state:string;course:any;courses:Course[];mappings:{plo_code:string|null;irm_level:string|null}[]};
const steps=['ข้อมูลรายวิชา','CLO / PLO','แผนรายสัปดาห์','การประเมิน','เอกสาร/ภาคผนวก','ตรวจความครบถ้วน','ส่งตรวจ'];
const emptyWeek=(n:number):WeekPlan=>({id:`week-${Date.now()}-${n}`,weekNo:n,topic:'',llo:'',cloLinks:'',activeLearning:'',assessmentActivity:'',rubric:'',evidence:''});
const emptyAssessment=():AssessmentItem=>({id:`assess-${Date.now()}`,name:'',weight:0,cloLinks:'',method:'',rubric:''});

export default function Tqf3Workspace(){
 const [step,setStep]=useState(0),[ctx,setCtx]=useState<Context|null>(null),[loading,setLoading]=useState(true),[courseCode,setCourseCode]=useState('');
 const [clos,setClos]=useState<Clo[]>([{id:'clo-1',text:'',status:'DRAFT'}]);
 const [weeks,setWeeks]=useState<WeekPlan[]>([emptyWeek(1)]);
 const [assessments,setAssessments]=useState<AssessmentItem[]>([emptyAssessment()]);
 const [references,setReferences]=useState(''),[testMethod,setTestMethod]=useState(''),[sampleExam,setSampleExam]=useState(''),[markingScheme,setMarkingScheme]=useState('');
 const [saved,setSaved]=useState(false),[aiNote,setAiNote]=useState('');
 async function load(code?:string){setLoading(true);try{const q=code?`?courseCode=${encodeURIComponent(code)}`:'';const r=await fetch(`/api/pilot-course-context${q}`,{cache:'no-store'});const j=await r.json();setCtx(j);if(j.course?.course_code)setCourseCode(j.course.course_code)}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 const acceptedClos=clos.filter(c=>c.status==='ACCEPTED'&&c.text.trim());
 const weightTotal=useMemo(()=>assessments.reduce((s,a)=>s+(Number.isFinite(a.weight)?a.weight:0),0),[assessments]);
 const weekComplete=weeks.filter(w=>w.llo.trim()&&w.cloLinks.trim()&&w.activeLearning.trim()&&w.rubric.trim()).length;
 const completion=useMemo(()=>{const checks=[!!ctx?.course?.course_code,acceptedClos.length>0,weekComplete===weeks.length&&weeks.length>0,assessments.some(a=>a.name.trim())&&weightTotal===100,!!testMethod.trim(),!!markingScheme.trim()];return Math.round(checks.filter(Boolean).length/checks.length*100)},[ctx,acceptedClos.length,weekComplete,weeks.length,assessments,weightTotal,testMethod,markingScheme]);
 function updateClo(id:string,text:string){setClos(v=>v.map(c=>c.id===id?{...c,text,status:'DRAFT'}:c));setSaved(false)}
 function addClo(){setClos(v=>[...v,{id:`clo-${Date.now()}`,text:'',status:'DRAFT'}])}
 function removeClo(id:string){setClos(v=>v.length===1?v:v.filter(c=>c.id!==id))}
 function acceptClo(id:string){setClos(v=>v.map(c=>c.id===id&&c.text.trim()?{...c,status:'ACCEPTED'}:c))}
 function addWeek(){setWeeks(v=>[...v,emptyWeek(v.length+1)]);setSaved(false)}
 function removeWeek(id:string){setWeeks(v=>v.length===1?v:v.filter(w=>w.id!==id).map((w,i)=>({...w,weekNo:i+1})));setSaved(false)}
 function duplicateWeek(id:string){setWeeks(v=>{const src=v.find(w=>w.id===id);if(!src)return v;return [...v,{...src,id:`week-${Date.now()}`,weekNo:v.length+1}]});setSaved(false)}
 function updateWeek(id:string,key:keyof WeekPlan,value:string){setWeeks(v=>v.map(w=>w.id===id?{...w,[key]:value}:w));setSaved(false)}
 function addAssessment(){setAssessments(v=>[...v,emptyAssessment()]);setSaved(false)}
 function updateAssessment(id:string,key:keyof AssessmentItem,value:string|number){setAssessments(v=>v.map(a=>a.id===id?{...a,[key]:value}:a));setSaved(false)}
 function removeAssessment(id:string){setAssessments(v=>v.length===1?v:v.filter(a=>a.id!==id));setSaved(false)}
 function askAi(scope:'clo'|'plan'|'assessment'){
  if(!ctx?.course?.description_th){setAiNote('AI advisory หยุดแบบ fail-closed เพราะยังไม่มี controlled course description ที่เพียงพอสำหรับการวิเคราะห์');return}
  const messages={clo:'AI CLO advisory runtime ยังไม่เชื่อมจริง: เมื่อเปิดใช้งานจะวิเคราะห์ course description + PLO context และเสนอ CLO โดยให้ Human Accept/Edit/Reject',plan:'AI Teaching Plan Reviewer ยังไม่เชื่อมจริง: เมื่อเปิดใช้งานจะตรวจ LLO↔CLO↔Active Learning↔Rubric↔Evidence รายสัปดาห์และอธิบาย alignment gaps',assessment:'AI Assessment Designer ยังไม่เชื่อมจริง: เมื่อเปิดใช้งานจะเสนอ assessment mix/weighting และตรวจ CLO coverage โดยผู้ใช้ปรับสัดส่วนได้'};setAiNote(messages[scope]);
 }
 function suggestWeights(){if(assessments.length===0)return;const base=Math.floor(100/assessments.length),rem=100-base*assessments.length;setAssessments(v=>v.map((a,i)=>({...a,weight:base+(i===v.length-1?rem:0)})));setAiNote('ระบบจัดสัดส่วน DEMO ให้รวม 100% แบบเท่า ๆ กันเพื่อทดสอบ UX เท่านั้น ไม่ใช่ข้อเสนอทางวิชาการจาก AI');setSaved(false)}
 function saveDemo(){try{localStorage.setItem('hepe-tqf3-demo-v2',JSON.stringify({courseCode,clos,weeks,assessments,references,testMethod,sampleExam,markingScheme,savedAt:new Date().toISOString()}));}catch{}setSaved(true)}
 const next=()=>setStep(s=>Math.min(steps.length-1,s+1)),back=()=>setStep(s=>Math.max(0,s-1));
 return <main className="guided-page"><header className="guided-header"><a href="/" className="back-home">← กลับ Academic Command Center</a><div><div className="eyebrow">HEPE-TQF3-WORKSPACE-02</div><h1>จัดทำ มคอ.3</h1><p>Flexible Weekly Plan + CLO/LLO Alignment + Active Learning + Rubric + Assessment Blueprint</p></div><div className="progress-box"><strong>{completion}%</strong><span>DEMO completeness</span></div></header>
 <div className="notice"><strong>NON-PRODUCTION / LOCAL DEMO WRITE ONLY</strong> Course context อ่านจาก controlled source; ข้อมูลที่แก้ในหน้านี้เก็บใน browser เท่านั้น ไม่มี canonical database write และไม่เข้าสู่ Audit Evidence โดยอัตโนมัติ</div>
 <nav className="stepper tqf3-stepper">{steps.map((s,i)=><button key={s} className={i===step?'current':i<step?'done':''} onClick={()=>setStep(i)}><span>{i<step?'✓':i+1}</span><b>{s}</b></button>)}</nav>
 <section className="guided-card"><div className="guided-title"><div><div className="eyebrow">ขั้นตอน {step+1} จาก {steps.length}</div><h2>{steps[step]}</h2></div><span className="demo-badge">CONTROLLED PILOT</span></div>
 {step===0&&<>{loading?<p className="help-text">กำลังอ่านทะเบียนรายวิชา...</p>:ctx?.state==='READY'?<><label className="field">เลือกรายวิชา<select value={courseCode} onChange={e=>load(e.target.value)}>{ctx.courses.map(c=><option key={c.course_code} value={c.course_code}>{c.course_code} · {c.title_th||c.title_en}</option>)}</select></label><div className="db-context"><div><span>รหัสวิชา</span><strong>{ctx.course.course_code}</strong></div><div><span>ชื่อวิชา</span><strong>{ctx.course.title_th||'—'}</strong></div><div><span>หน่วยกิต</span><strong>{ctx.course.credit_pattern||ctx.course.credit_value||'—'}</strong></div><div><span>กลุ่มวิชา</span><strong>{ctx.course.group_name_th||'—'}</strong></div></div><div className="description-box"><div><strong>คำอธิบายรายวิชา</strong><span className="source-badge">DATABASE</span></div>{ctx.course.description_th?<p>{ctx.course.description_th}</p>:<p className="missing-data">ยังไม่มี controlled course description — ระบบไม่สร้างข้อความทดแทน</p>}</div></>:<div className="firewall">อ่าน controlled course context ไม่สำเร็จ: {ctx?.state||'UNKNOWN'}</div>}</>}
 {step===1&&<><div className="ai-advisory"><div><div className="eyebrow">AI ADVISORY</div><h3>CLO Builder</h3><p>AI เป็นผู้เสนอเท่านั้น ผู้สอนเป็นผู้ยืนยันทุก CLO</p></div><button onClick={()=>askAi('clo')}>วิเคราะห์ CLO</button></div>{aiNote&&<div className="ai-note">{aiNote}</div>}<div className="clo-list">{clos.map((c,i)=><article className="clo-card" key={c.id}><div className="clo-head"><strong>CLO{i+1}</strong><span className={c.status==='ACCEPTED'?'clo-status accepted':'clo-status'}>{c.status==='ACCEPTED'?'ยืนยันแล้ว':'รอการยืนยัน'}</span></div><textarea rows={3} value={c.text} onChange={e=>updateClo(c.id,e.target.value)} placeholder={`เขียน CLO${i+1}`}/><div className="clo-actions"><button onClick={()=>acceptClo(c.id)} disabled={!c.text.trim()}>✓ ยอมรับ</button><button onClick={()=>removeClo(c.id)} disabled={clos.length===1}>ลบ</button></div></article>)}</div><button className="add-clo" onClick={addClo}>＋ เพิ่ม CLO</button><div className="mapping-preview"><strong>PLO / I-R-M จาก controlled curriculum</strong>{ctx?.mappings?.length?<div>{ctx.mappings.map((m,i)=><span key={i}>{m.plo_code||'PLO?'} · {m.irm_level||'—'}</span>)}</div>:<p>ยังไม่พบ mapping</p>}<small>เป็นบริบทประกอบ ไม่ใช่การสร้าง CLO→PLO mapping ใหม่</small></div></>}
 {step===2&&<><div className="ai-advisory"><div><div className="eyebrow">AI TEACHING PLAN REVIEWER</div><h3>ตรวจความสอดคล้องแผนรายสัปดาห์</h3><p>เป้าหมายคือ LLO → CLO → Active Learning → Assessment Activity → Rubric → Evidence ในแต่ละสัปดาห์</p></div><button onClick={()=>askAi('plan')}>วิเคราะห์แผน</button></div>{aiNote&&<div className="ai-note">{aiNote}</div>}<div className="week-list">{weeks.map(w=><article className="week-card" key={w.id}><div className="week-head"><div><strong>สัปดาห์ที่ {w.weekNo}</strong><small>{w.llo&&w.cloLinks&&w.activeLearning&&w.rubric?'alignment fields พร้อมตรวจ':'ยังกรอกไม่ครบ'}</small></div><div><button onClick={()=>duplicateWeek(w.id)}>ทำสำเนา</button><button onClick={()=>removeWeek(w.id)} disabled={weeks.length===1}>ลบ</button></div></div><div className="week-grid"><label>หัวข้อ/สาระ<input value={w.topic} onChange={e=>updateWeek(w.id,'topic',e.target.value)}/></label><label>LLOs<input value={w.llo} onChange={e=>updateWeek(w.id,'llo',e.target.value)} placeholder="เช่น LLO1, LLO2"/></label><label>Link CLOs<input value={w.cloLinks} onChange={e=>updateWeek(w.id,'cloLinks',e.target.value)} placeholder="เช่น CLO1, CLO3"/></label><label>Active Learning<textarea rows={2} value={w.activeLearning} onChange={e=>updateWeek(w.id,'activeLearning',e.target.value)}/></label><label>กิจกรรมประเมิน<textarea rows={2} value={w.assessmentActivity} onChange={e=>updateWeek(w.id,'assessmentActivity',e.target.value)}/></label><label>Rubric / เกณฑ์ประเมิน<textarea rows={2} value={w.rubric} onChange={e=>updateWeek(w.id,'rubric',e.target.value)}/></label><label className="week-wide">Evidence ที่คาดว่าจะเกิด<input value={w.evidence} onChange={e=>updateWeek(w.id,'evidence',e.target.value)}/></label></div></article>)}</div><button className="add-clo" onClick={addWeek}>＋ เพิ่มสัปดาห์</button></>}
 {step===3&&<><div className="assessment-top"><div><h3>Assessment Weight Designer</h3><p>เพิ่ม/ลดองค์ประกอบได้เอง ระบบตรวจผลรวม 100%</p></div><div><button onClick={suggestWeights}>Rebalance DEMO</button><button onClick={()=>askAi('assessment')}>AI วิเคราะห์</button></div></div>{aiNote&&<div className="ai-note">{aiNote}</div>}<div className={weightTotal===100?'weight-total ok':'weight-total'}><span>คะแนนรวม</span><strong>{weightTotal}%</strong><small>{weightTotal===100?'พร้อมตรวจ':'ต้องปรับให้รวม 100%'}</small></div><div className="assessment-list">{assessments.map((a,i)=><article className="assessment-card" key={a.id}><div className="assessment-head"><strong>องค์ประกอบที่ {i+1}</strong><button onClick={()=>removeAssessment(a.id)} disabled={assessments.length===1}>ลบ</button></div><div className="assessment-grid"><label>ชื่อรายการ<input value={a.name} onChange={e=>updateAssessment(a.id,'name',e.target.value)}/></label><label>สัดส่วน (%)<input type="number" min="0" max="100" value={a.weight} onChange={e=>updateAssessment(a.id,'weight',Number(e.target.value))}/></label><label>Link CLOs<input value={a.cloLinks} onChange={e=>updateAssessment(a.id,'cloLinks',e.target.value)}/></label><label>วิธีประเมิน<input value={a.method} onChange={e=>updateAssessment(a.id,'method',e.target.value)}/></label><label className="assessment-wide">Rubric / scoring criteria<textarea rows={2} value={a.rubric} onChange={e=>updateAssessment(a.id,'rubric',e.target.value)}/></label></div></article>)}</div><button className="add-clo" onClick={addAssessment}>＋ เพิ่มองค์ประกอบคะแนน</button></>}
 {step===4&&<><p className="help-text">กำหนดทรัพยากร วิธีทดสอบ และภาคผนวกสำหรับเอกสาร มคอ.3</p><div className="appendix-grid"><label>ตำรา/เอกสาร/ทรัพยากรแนะนำ<textarea rows={3} value={references} onChange={e=>setReferences(e.target.value)} placeholder="ระบุแหล่งที่ผู้สอนตรวจสอบแล้ว"/></label><label>วิธีการทดสอบ / Assessment Blueprint<textarea rows={3} value={testMethod} onChange={e=>setTestMethod(e.target.value)}/></label><label>ตัวอย่างข้อสอบ / งานประเมิน<textarea rows={4} value={sampleExam} onChange={e=>setSampleExam(e.target.value)}/></label><label>Marking Scheme / เกณฑ์ให้คะแนน<textarea rows={4} value={markingScheme} onChange={e=>setMarkingScheme(e.target.value)}/></label></div><p className="note">AI อาจช่วยเสนอรายการอ้างอิงในอนาคต แต่ต้องแสดง provenance และห้ามสร้าง citation ที่ตรวจสอบไม่ได้</p></>}
 {step===5&&<><div className="review-list"><div><span>Course context</span><b>{ctx?.course?.course_code?'พร้อมตรวจ':'ยังขาด'}</b></div><div><span>CLO ที่ Human ยืนยัน</span><b>{acceptedClos.length?`${acceptedClos.length} ข้อ`:'ยังไม่มี'}</b></div><div><span>Weekly Plan</span><b>{weekComplete===weeks.length&&weeks.length?`${weekComplete}/${weeks.length} สัปดาห์พร้อมตรวจ`:`${weekComplete}/${weeks.length} สัปดาห์`}</b></div><div><span>Assessment Weight</span><b>{weightTotal===100?'100%':'ยังไม่ครบ 100%'}</b></div><div><span>วิธีการทดสอบ</span><b>{testMethod.trim()?'มีข้อมูล':'ยังขาด'}</b></div><div><span>Marking Scheme</span><b>{markingScheme.trim()?'มีข้อมูล':'ยังขาด'}</b></div></div><p className="note">“พร้อมตรวจ” เป็น completeness state เท่านั้น ไม่ใช่ PASS และไม่ใช่ Audit Evidence</p></>}
 {step===6&&<div className="handoff"><h3>DEMO draft พร้อมเข้าสู่ Human Review เมื่อผ่าน completeness gate</h3><p>Canonical write, publication, activation, AI approval และ Audit Evidence admission ยังปิดทั้งหมด การเชื่อม TQF5 จะถูกเปิดตาม lifecycle contract หลังมี controlled implementation.</p><a className="primary-action" href="/">กลับ Academic Command Center →</a></div>}
 <div className="guided-actions"><button onClick={back} disabled={step===0}>← ย้อนกลับ</button><div><button className="secondary" onClick={saveDemo}>บันทึก DEMO</button>{step<steps.length-1&&<button className="primary" onClick={next}>ถัดไป →</button>}</div></div><div className="save-state">{saved?'บันทึก DEMO ใน browser แล้ว':'ยังไม่ได้บันทึก DEMO'}</div></section>
 <footer className="guided-footer">LOCAL DEMO WRITE ONLY · AI ADVISORY ONLY · HUMAN AUTHORITY PRESERVED · PRODUCTION NOT TOUCHED · AUDIT EVIDENCE ADMISSION DISABLED</footer></main>}
