import { demoTickets, SUPPORT_STATUSES } from '../../support-model';

export default async function TicketDetail({params}:{params:Promise<{ticketId:string}>}){
 const {ticketId}=await params; const t=demoTickets.find(x=>x.ticket_id===ticketId);
 return <main className="support-shell"><header className="support-top"><div><div className="eyebrow">TICKET DETAIL</div><h1>{t?t.ticket_number:'Support Ticket'}</h1><p>{t?t.title:'Local browser-created tickets remain on the creating browser and are not persisted to controlled storage in SUPPORT-01.'}</p></div><div className="support-badges"><span className="support-badge">{t?.support_status||'LOCAL CANDIDATE'}</span><span className="support-badge">NON-PRODUCTION</span></div></header>
 <div className="support-notice"><strong>Support record only.</strong> Ticket นี้ไม่ใช่ Formal Finding, Approved Decision, Audit Evidence หรือ canonical correction โดยอัตโนมัติ</div>
 {t?<section className="support-grid support-grid-2"><article className="support-card"><h2>Issue Context</h2><div className="support-list"><div className="support-row"><span>Category</span><strong>{t.ticket_category}</strong></div><div className="support-row"><span>Severity</span><strong>{t.severity}</strong></div><div className="support-row"><span>Module</span><strong>{t.module_code}</strong></div><div className="support-row"><span>Page</span><strong>{t.page_path}</strong></div><div className="support-row"><span>Course</span><strong>{t.course_code||'—'}</strong></div><div className="support-row"><span>Provenance</span><strong>{t.provenance_status}</strong></div></div><h3 style={{marginTop:16}}>Description</h3><p>{t.description}</p></article><article className="support-card"><h2>Lifecycle</h2><div className="support-timeline">{SUPPORT_STATUSES.map(s=><div className="support-step" key={s}><strong>{s}</strong><small>{s===t.support_status?'CURRENT / SYNTHETIC DISPLAY':'candidate transition'}</small></div>)}</div></article></section>:<div className="support-empty">ไม่พบ persistent ticket record สำหรับ {ticketId}. SUPPORT-01 ยังไม่มี support database schema; local tickets ไม่ถูกส่งออกจาก browser.</div>}
 <section className="support-grid support-grid-2" style={{marginTop:16}}><article className="support-card"><h2>Technical Traceability</h2><p>รองรับ logical links ไป Programme, Curriculum Version, Course Offering, Module, GitHub Issue/Commit/PR, Vercel Deployment, Test Run, Evidence Candidate และ Reconciliation Item โดยยังไม่สร้าง persistent link table.</p><div className="support-status">TRACEABILITY CONTRACT CANDIDATE</div></article><article className="support-card support-ai"><span className="support-status">AI ADVISORY ONLY</span><h2 style={{marginTop:8}}>Support Advisor</h2><p>สามารถเสนอ category/severity/troubleshooting/duplicate candidate ได้ แต่ไม่มีปุ่ม close, approve, authority grant, evidence admission หรือ canonical mutation.</p></article></section>
 <div className="support-actions" style={{marginTop:16}}><a className="support-action" href="/support">Support Center</a><a className="support-action" href="/support/triage">Triage Queue</a></div></main>
}
