import { createServerClient } from "@supabase/ssr";
import { cookies } from "next/headers";

export const dynamic = "force-dynamic";

type TeachingState = { academic_year:string; term_code:string; course_code:string; source_person_label:string|null; academic_person_id:string|null; disposition:string|null; verification_status:string|null; creates_system_authority:boolean|null; };
type WorkspaceSnapshot = { state:string; authenticated:boolean; userEmail?:string; academicPersonId?:string; teachingStates:TeachingState[]; };

async function loadWorkspaceSnapshot(): Promise<WorkspaceSnapshot> {
  const url=process.env.NEXT_PUBLIC_SUPABASE_URL; const key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;
  if(!url||!key) return {state:"RUNTIME_NOT_CONFIGURED",authenticated:false,teachingStates:[]};
  const cookieStore=await cookies(); const supabase=createServerClient(url,key,{cookies:{getAll(){return cookieStore.getAll();},setAll(){}}});
  const {data:authData}=await supabase.auth.getUser(); const user=authData.user; if(!user) return {state:"AUTH_REQUIRED",authenticated:false,teachingStates:[]};
  const {data:actorRows,error:actorError}=await supabase.from("actors").select("actor_id").eq("external_identity_subject",user.id).eq("status","ACTIVE").limit(1);
  if(actorError||!actorRows?.[0]) return {state:"ACTOR_BINDING_NOT_READABLE",authenticated:true,userEmail:user.email,teachingStates:[]};
  const {data:bindingRows,error:bindingError}=await supabase.from("academic_person_actor_bindings").select("academic_person_id,binding_status").eq("actor_id",actorRows[0].actor_id).eq("binding_status","VERIFIED").limit(1);
  if(bindingError||!bindingRows?.[0]) return {state:"ACADEMIC_PERSON_BINDING_NOT_READABLE",authenticated:true,userEmail:user.email,teachingStates:[]};
  const academicPersonId=bindingRows[0].academic_person_id;
  const {data:states,error:stateError}=await supabase.from("mr30_effective_teaching_states").select("academic_year,term_code,course_code,source_person_label,academic_person_id,disposition,verification_status,creates_system_authority").eq("academic_person_id",academicPersonId).eq("academic_year","2569").eq("term_code","1").order("course_code");
  return {state:stateError?"TEACHING_READ_PARTIAL":"VERIFIED_READ",authenticated:true,userEmail:user.email,academicPersonId,teachingStates:(states??[]) as TeachingState[]};
}
function Pill({children}:{children:React.ReactNode}){return <span style={{display:"inline-flex",padding:"5px 10px",borderRadius:999,border:"1px solid #cbd5e1",background:"#f8fafc",fontSize:12,fontWeight:700,color:"#475569"}}>{children}</span>}
function Metric({label,value,note}:{label:string;value:string|number;note?:string}){return <article style={{background:"white",border:"1px solid #e2e8f0",borderRadius:18,padding:18}}><div style={{fontSize:12,color:"#64748b"}}>{label}</div><div style={{fontSize:28,fontWeight:850,marginTop:6}}>{value}</div>{note&&<div style={{fontSize:12,color:"#64748b",marginTop:6,lineHeight:1.5}}>{note}</div>}</article>}

export default async function Home(){
 const snapshot=await loadWorkspaceSnapshot(); const verifiedStates=snapshot.teachingStates.filter(s=>(s.verification_status??"").includes("VERIFIED")).length; const courseCount=new Set(snapshot.teachingStates.map(s=>s.course_code)).size;
 if(!snapshot.authenticated)return <main style={{minHeight:"100vh",display:"grid",placeItems:"center",padding:24,background:"linear-gradient(135deg,#f0fdfa,#f8fafc 55%,#eff6ff)"}}><section style={{maxWidth:720,background:"white",border:"1px solid #e2e8f0",borderRadius:24,padding:30}}><div style={{fontSize:13,fontWeight:800,color:"#0f766e"}}>HEPE · ACADEMIC WORKSPACE · NON-PRODUCTION</div><h1>พื้นที่ทำงานอาจารย์</h1><p style={{color:"#475569",lineHeight:1.8}}>กรุณาเข้าสู่ระบบก่อน ระบบจะพาเข้าสู่หน้าหลักที่แสดงงานประจำภาคเรียน รายวิชา และสถานะเอกสาร</p><a href="/login">เข้าสู่ระบบ</a></section></main>;
 const timeline=[["ก่อนเปิดภาค","เตรียมข้อมูลรายวิชาและแผนการสอน"],["ต้นภาคเรียน","จัดทำเอกสารต้นภาคและตรวจความครบถ้วน"],["ระหว่างภาค","บันทึกการสอน หลักฐาน และผลการประเมิน"],["สิ้นสุดภาค","สรุปผลการเรียนรู้และผลการดำเนินงาน"],["หลังสิ้นสุดภาค","ปิดภาคและส่งสัญญาณเข้าสู่การปรับปรุงหลักสูตร"]];
 return <main style={{minHeight:"100vh",background:"#f8fafc",color:"#0f172a"}}><div style={{maxWidth:1240,margin:"0 auto",padding:"28px 22px 48px"}}>
 <header style={{display:"flex",justifyContent:"space-between",gap:18,flexWrap:"wrap"}}><div><div style={{fontSize:13,fontWeight:800,color:"#0f766e"}}>HEPE · POST-LOGIN HOME · NON-PRODUCTION</div><h1 style={{margin:"6px 0"}}>พื้นที่ทำงานอาจารย์</h1><p style={{margin:0,color:"#64748b"}}>ภาคเรียนนี้ต้องทำอะไร งานไปถึงไหน และอะไรควรทำต่อ</p></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><Pill>ปีการศึกษา 2569</Pill><Pill>ภาคเรียน 1</Pill><Pill>{snapshot.state}</Pill></div></header>
 <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:14,marginTop:24}}><Metric label="รายวิชาที่พบใน Teaching State" value={courseCount}/><Metric label="Teaching State VERIFIED" value={verifiedStates} note={`ทั้งหมด ${snapshot.teachingStates.length} records`}/><Metric label="ความครบถ้วน มคอ." value="READ MODEL PENDING" note="ไม่สร้างเปอร์เซ็นต์จำลอง"/><Metric label="งานเร่งด่วน" value="READ MODEL PENDING" note="รอ deadline/completeness engine ที่ตรวจสอบได้"/></section>
 <section style={{marginTop:22,background:"white",border:"1px solid #e2e8f0",borderRadius:20,padding:20}}><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div><h2 style={{margin:0}}>Timeline การจัดทำ มคอ.</h2><p style={{fontSize:13,color:"#64748b"}}>วงจรที่ LOCK ไว้; สถานะจริงรอ M.Kor read model</p></div><Pill>NO MOCK STATUS</Pill></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:12}}>{timeline.map(([phase,description],i)=><div key={phase} style={{padding:16,borderRadius:16,border:"1px solid #e2e8f0"}}><div style={{fontSize:12,fontWeight:800,color:"#0f766e"}}>STEP {i+1}</div><strong>{phase}</strong><p style={{fontSize:13,color:"#64748b"}}>{description}</p><small>READ MODEL PENDING</small></div>)}</div></section>
 <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(260px,1fr))",gap:14,marginTop:22}}><a href="/teaching" style={{textDecoration:"none",color:"inherit",background:"white",border:"1px solid #bbf7d0",borderRadius:20,padding:20}}><strong>รายวิชาของฉัน</strong><p style={{color:"#64748b"}}>Verified Teaching Context และ provenance</p></a><a href="/mkor" style={{textDecoration:"none",color:"inherit",background:"white",border:"1px solid #99f6e4",borderRadius:20,padding:20}}><div style={{fontSize:12,fontWeight:800,color:"#0f766e"}}>PRIMARY WORKSPACE</div><h3>มคอ.ของฉัน</h3><p style={{color:"#64748b"}}>เปิด M.Kor workspace entry จากรายวิชาที่ระบบอ่านได้จริง โดยยังไม่สร้าง completeness จำลอง</p></a><div style={{background:"white",border:"1px solid #e2e8f0",borderRadius:20,padding:20}}><strong>เตรียมปรับปรุงหลักสูตร</strong><p style={{color:"#64748b"}}>Signal → Evidence → Analysis → Priority → Recommendation → Human Decision → Follow-up</p></div></section>
 {snapshot.teachingStates.length>0&&<section style={{marginTop:22,background:"white",border:"1px solid #e2e8f0",borderRadius:20,padding:20}}><h2>รายวิชาที่ระบบพบในภาคเรียนนี้</h2><p style={{fontSize:13,color:"#64748b"}}>Verified System Data; ไม่ตีความเป็น authority เพิ่มเติม</p><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:10}}>{snapshot.teachingStates.slice(0,6).map(s=><article key={`${s.course_code}-${s.disposition}`} style={{padding:14,border:"1px solid #e2e8f0",borderRadius:14}}><strong>{s.course_code}</strong><div style={{fontSize:13,color:"#64748b"}}>{s.source_person_label??"—"}</div></article>)}</div></section>}
 <section style={{marginTop:22,padding:18,borderRadius:18,background:"#eef2ff",border:"1px solid #c7d2fe"}}><strong>Programme Administration / Governance</strong><p style={{color:"#475569"}}>secondary navigation ตามบทบาท</p><div style={{display:"flex",gap:10,flexWrap:"wrap"}}><a href="/governance/course-equivalence">Course Equivalence</a><a href="/governance/responsibilities">Academic Responsibility</a><a href="/governance/evidence">Evidence Explorer</a></div></section>
 <footer style={{marginTop:26,fontSize:12,color:"#64748b"}}>VERIFIED SYSTEM DATA where available · NON-PRODUCTION · No automatic Audit Evidence Admission · Human authority preserved.</footer>
 </div></main>;
}
