const modules = [
  ['programme','Programme Overview'],['curriculum','Curriculum Overview'],['traceability','PLO / CLO Traceability'],['mapping','Curriculum Mapping / I-R-M'],['teaching','Learning & Teaching'],['assessment','Assessment'],['plan-actual','Teaching Plan vs Actual'],['reviews','Review Queue'],['decisions','Approval / Decision Workspace'],['evidence','Evidence Explorer'],['findings','Findings & Improvement'],['qa','QA / CPRR Readiness'],['tasks','Academic Tasks / Approval Center'],['ai','AI Advisory / Academic Intelligence'],['analytics','Analytics & Insights'],['calendar','Academic Calendar'],['audit','Provenance / Audit Trail'],['runtime','Runtime / Connector Health'],['outbox','Outbox Queue'],['reconciliation','Reconciliation Workspace'],['governance','System Governance / Gate Status'],['welcome','Welcome / Authentication Entry']
];

const primary = new Set(['programme','curriculum','traceability','mapping','teaching','assessment','plan-actual','reviews','evidence','qa','decisions','tasks']);

export default function Home(){
 return <main className="shell">
  <aside className="sidebar">
   <div className="brand-kicker">HEPE · BED-HEPE</div><div className="brand">Academic Command Center</div>
   <p className="brand-sub">Curriculum governance, evidence, academic authority and quality assurance in one controlled workspace.</p><div className="env">● NON-PRODUCTION</div>
   <nav className="nav" aria-label="HEPE modules"><a className="active" href="/">Command Center</a><div className="nav-group">Core academic workflow</div>{modules.filter(([s])=>primary.has(s)).map(([s,l])=><a key={s} href={`/${s}`}>{l}</a>)}<div className="nav-group">Intelligence & governance</div>{modules.filter(([s])=>!primary.has(s)).map(([s,l])=><a key={s} href={`/${s}`}>{l}</a>)}</nav>
  </aside>
  <section className="workspace">
   <header className="topline"><div><div className="eyebrow">HEPE Curriculum Governance & Development</div><h1 className="page-title">Programme Command Center</h1><p className="page-subtitle">Evidence-first academic governance for curriculum, outcomes, teaching, assessment, reviews, evidence and human-authority decisions. Only controlled or verified information is presented as fact.</p></div><div className="contexts"><span className="chip">Academic Year · 2569</span><span className="chip">Programme · BED-HEPE</span><span className="chip">Curriculum · 2567</span></div></header>
   <section className="hero-modern" aria-labelledby="hero-title"><div className="brand-kicker">Master UI Prototype · Controlled Pilot Critical Path</div><h2 id="hero-title">One academic governance platform, from curriculum structure to teaching evidence and evidence-backed decisions.</h2><p>The interface brings academic workflows forward while Supabase, Vercel, GitHub and other implementation infrastructure remain behind the experience. Human academic authority and RLS boundaries remain unchanged.</p><div className="hero-actions"><a className="button" href="/plan-actual">Open Plan vs Actual</a><a className="button secondary" href="/reviews">Open Review Queue</a><a className="button secondary" href="/evidence">Explore Evidence</a><a className="button secondary" href="/mapping">Open PLO/CLO Mapping</a></div></section>
   <div className="notice">Controlled Preview · NON-PRODUCTION · Authenticated RLS reads only · Plan-vs-actual analysis is advisory and does not constitute academic approval or compliance certification.</div>
   <section aria-label="Programme governance status" className="grid g4">{[['Governance Foundation','CONTROLLED','REL-01 / REL-02'],['Persistence & RLS','VERIFIED','REL-02A controlled foundation'],['Application Runtime','PASS','REL-03 controlled / reconciled'],['Pilot Critical Path','IN PROGRESS','Teaching / assessment / plan-vs-actual materialization']].map(([a,b,c])=><article className="card interactive" key={a}><div className="label">{a}</div><div className="value">{b}</div><div className="note">{c}</div></article>)}</section>
   <div className="grid g2" style={{marginTop:14}}><article className="card"><h2 className="section-title">Programme Readiness</h2>{[['Curriculum baseline','Controlled'],['Evidence governance','Controlled'],['Authority / RLS','Verified'],['Durable persistence','Verified'],['Authenticated runtime binding','Verified — synthetic preview'],['Teaching & assessment shell','Pilot build in progress']].map(([a,b])=><div className="row" key={a}><span>{a}</span><span className="status status-ok">{b}</span></div>)}</article><article className="card"><h2 className="section-title">Governance Gate Register</h2>{[['REL-01','PASS'],['REL-02','PASS'],['REL-02A','PASS + documented repair'],['REL-03','CONTROLLED / RECONCILED PASS'],['WEB-02','CONTROLLED / RECONCILED PASS'],['PILOT-MASTER-01','IN PROGRESS'],['Production','NOT AUTHORIZED']].map(([a,b])=><div className="row" key={a}><span>{a}</span><span className="status">{b}</span></div>)}</article></div>
   <section style={{marginTop:14}} aria-labelledby="workflow-title"><div className="eyebrow">Academic workflow</div><h2 className="section-title" id="workflow-title" style={{marginTop:6}}>Core workspaces</h2><div className="grid g3">{[['PLO / CLO Mapping','Trace outcomes, course relationships and I-R-M without changing controlled mappings.','mapping'],['Learning & Teaching','Inspect planned activities, CLO links, assessment links and delivery evidence under RLS.','teaching'],['Assessment','Inspect controlled assessment versions and outcome-alignment evidence.','assessment'],['Plan vs Actual','Compare planned learning activities with recorded delivery and controlled links without fabricating missing evidence.','plan-actual'],['Review Queue','Authority-aware academic review with RLS-preserving runtime reads.','reviews'],['Evidence Explorer','Provenance, evidence type, verification and admissibility status.','evidence'],['Approval Center','Human-governed decision context; AI cannot approve academic decisions.','decisions'],['QA / CPRR','Quality assurance and programme review workspace without fabricated scores.','qa'],['AI Advisory','Academic intelligence is advisory only and cannot replace human authority.','ai']].map(([a,b,s])=><article className="card interactive" key={a}><span className="screen-tag">Academic workspace</span><div className="value" style={{fontSize:17}}>{a}</div><p className="note">{b}</p><a className="note" href={`/${s}`} style={{display:'inline-block',marginTop:10,fontWeight:750,color:'var(--brand)'}}>Open workspace →</a></article>)}</div></section>
   <article className="card" style={{marginTop:14}}><div className="eyebrow">Platform map</div><h2 className="section-title" style={{marginTop:6}}>Master screen families and workspaces</h2><div className="grid g4">{modules.map(([s,l])=><a className="module-link" key={s} href={`/${s}`}>{l}</a>)}</div></article>
   <footer className="footer-note">HEPE Curriculum Governance & Development · HEPE-PILOT-MASTER-01 · Evidence-first · Human academic authority preserved · NON-PRODUCTION · TEST DATA ONLY.</footer>
  </section>
 </main>
}
