export type Role='STUDENT'|'ADVISOR'|'EPLC_COORDINATOR'|'VERIFIER'|'PROGRAMME_COMMITTEE'|'PROGRAMME_CHAIR'|'SYSTEM_ADMIN';
export type Permission='READ_SELF'|'READ_COHORT'|'SUBMIT_EVIDENCE'|'VERIFY_EVIDENCE'|'REVIEW_CLEARANCE'|'MANAGE_REQUIREMENTS'|'READ_AUDIT';
export const rolePermissions: Record<Role,Permission[]>={
 STUDENT:['READ_SELF','SUBMIT_EVIDENCE'],
 ADVISOR:['READ_COHORT'],
 EPLC_COORDINATOR:['READ_COHORT'],
 VERIFIER:['READ_COHORT','VERIFY_EVIDENCE'],
 PROGRAMME_COMMITTEE:['READ_COHORT','REVIEW_CLEARANCE','READ_AUDIT'],
 PROGRAMME_CHAIR:['READ_COHORT','REVIEW_CLEARANCE','MANAGE_REQUIREMENTS','READ_AUDIT'],
 SYSTEM_ADMIN:['READ_COHORT','MANAGE_REQUIREMENTS','READ_AUDIT']
};
export function can(role:Role,permission:Permission){return rolePermissions[role].includes(permission)}
