import { createHepeServerClient } from './server-supabase';
export const PILOT_PROGRAMME_CODE='25510071103503';
export const PILOT_VERSION_CODE='2567-SOURCEB-VALIDATION';
export const SOURCE_SHA='f580fec8bb661181cbc0dff3c58473563c4b723f2dde5e863d91667ea4ec3557';
type AnyRow=Record<string,any>;
export async function loadPilotReadModel(){
 const supabase=await createHepeServerClient(); if(!supabase)return {state:'RUNTIME_BINDING_UNAVAILABLE' as const};
 const {data:userData}=await supabase.auth.getUser(); if(!userData.user)return {state:'AUTH_REQUIRED' as const};
 const {data:programme}=await supabase.from('programmes').select('programme_id,programme_code,title_th,title_en,status_code').eq('programme_code',PILOT_PROGRAMME_CODE).maybeSingle(); if(!programme)return {state:'AUTHORITY_DENIED' as const};
 const {data:version}=await supabase.from('curriculum_versions').select('curriculum_version_id,version_code,status_code,is_current,approved_at,activated_at,effective_academic_period_id').eq('programme_id',programme.programme_id).eq('version_code',PILOT_VERSION_CODE).maybeSingle(); if(!version)return {state:'AUTHORITY_DENIED' as const};
 const results=await Promise.all([
  supabase.from('curriculum_courses').select('curriculum_course_id,course_id,course_role,recommended_year,recommended_term,display_order').eq('curriculum_version_id',version.curriculum_version_id),
  supabase.from('courses').select('course_id,course_code,title_th,title_en,credit_value,status_code'),
  supabase.from('course_credit_patterns').select('curriculum_course_id,raw_credit_notation,credit_units,lecture_hours,practice_hours,self_study_hours,source_page,source_locator,verification_status'),
  supabase.from('curriculum_course_groups').select('course_group_id,group_code,group_name_th,group_name_en,parent_group_id,group_type,sequence_no,required_credits,selection_rule_raw,source_page,source_locator,verification_status').eq('curriculum_version_id',version.curriculum_version_id),
  supabase.from('curriculum_course_group_memberships').select('curriculum_course_id,course_group_id,membership_type,source_page,source_locator,verification_status'),
  supabase.from('study_plan_entries').select('study_plan_entry_id,academic_year_no,term_code,sequence_no,entry_kind,curriculum_course_id,course_group_id,choice_pool_id,raw_entry_text,required_credits,source_page,source_locator,verification_status').eq('curriculum_version_id',version.curriculum_version_id),
  supabase.from('curriculum_course_plo_mappings').select('course_plo_mapping_id,curriculum_course_id,plo_id,irm_level,source_page,source_locator,verification_status').eq('curriculum_version_id',version.curriculum_version_id),
  supabase.from('outcomes').select('outcome_id,canonical_code,outcome_type,status_code').eq('programme_id',programme.programme_id),
  supabase.from('curricular_provenance_bindings').select('entity_type,entity_id,source_document_id,source_sha256,source_locator,ingestion_batch_id,candidate_record_id,verification_status').eq('programme_id',programme.programme_id),
  supabase.from('v_hepe_ingest_validation_summary').select('*').eq('programme_code',PILOT_PROGRAMME_CODE).eq('version_code',PILOT_VERSION_CODE).maybeSingle(),
  supabase.from('course_description_versions').select('curriculum_course_id,version_no,description_th,description_en,status_code,verification_status,authority_status,source_reference,source_sha256,source_locator,is_current,approved_at,activated_at').eq('is_current',true),
 ]);
 const [ccR,cR,pR,gR,mR,sR,mapR,oR,provR,sumR,descR]=results;
 const ccRows=(ccR.data??[]) as AnyRow[],courseRows=(cR.data??[]) as AnyRow[],patternRows=(pR.data??[]) as AnyRow[],groupRows=(gR.data??[]) as AnyRow[],memberRows=(mR.data??[]) as AnyRow[],outcomeRows=(oR.data??[]) as AnyRow[],descRows=(descR.data??[]) as AnyRow[];
 const courseById:Map<string,AnyRow>=new Map(courseRows.map(x=>[String(x.course_id),x])); const ccById:Map<string,AnyRow>=new Map(ccRows.map(x=>[String(x.curriculum_course_id),x])); const patternByCC:Map<string,AnyRow>=new Map(patternRows.map(x=>[String(x.curriculum_course_id),x])); const groupById:Map<string,AnyRow>=new Map(groupRows.map(x=>[String(x.course_group_id),x])); const memberByCC:Map<string,AnyRow>=new Map(memberRows.map(x=>[String(x.curriculum_course_id),x])); const outcomeById:Map<string,AnyRow>=new Map(outcomeRows.map(x=>[String(x.outcome_id),x])); const descByCC:Map<string,AnyRow>=new Map(descRows.map(x=>[String(x.curriculum_course_id),x]));
 const courseList=(ccRows.map((x):AnyRow=>{const c:AnyRow=courseById.get(String(x.course_id))??{};const p:AnyRow=patternByCC.get(String(x.curriculum_course_id))??{};const mm:AnyRow=memberByCC.get(String(x.curriculum_course_id))??{};const g:AnyRow=groupById.get(String(mm.course_group_id))??{};const d:AnyRow=descByCC.get(String(x.curriculum_course_id))??{};const row:AnyRow={...x,...c,credit_pattern:p.raw_credit_notation??null,lecture_hours:p.lecture_hours??null,practice_hours:p.practice_hours??null,self_study_hours:p.self_study_hours??null,group_code:g.group_code??null,group_name_th:g.group_name_th??null,group_name_en:g.group_name_en??null,source_page:mm.source_page??p.source_page??null,source_locator:mm.source_locator??p.source_locator??null,verification_status:mm.verification_status??p.verification_status??null,description_th:d.description_th??null,description_en:d.description_en??null,description_version_no:d.version_no??null,description_status_code:d.status_code??null,description_verification_status:d.verification_status??null,description_authority_status:d.authority_status??null,description_source_reference:d.source_reference??null,description_source_sha256:d.source_sha256??null,description_source_locator:d.source_locator??null,description_is_current:d.is_current??false,description_approved_at:d.approved_at??null,description_activated_at:d.activated_at??null};return row;}) as AnyRow[]).sort((a,b)=>String(a.course_code).localeCompare(String(b.course_code)));
 const studyList=(((sR.data??[]) as AnyRow[]).map((x):AnyRow=>{const ccx:AnyRow=ccById.get(String(x.curriculum_course_id))??{};const c:AnyRow=courseById.get(String(ccx.course_id))??{};const g:AnyRow=groupById.get(String(x.course_group_id))??{};const row:AnyRow={...x,course_code:c.course_code??null,title_th:c.title_th??null,group_name_th:g.group_name_th??null};return row;}) as AnyRow[]).sort((a,b)=>(Number(a.academic_year_no)-Number(b.academic_year_no))||String(a.term_code).localeCompare(String(b.term_code))||(Number(a.sequence_no)-Number(b.sequence_no)));
 const mappingList=(((mapR.data??[]) as AnyRow[]).map((x):AnyRow=>{const ccx:AnyRow=ccById.get(String(x.curriculum_course_id))??{};const c:AnyRow=courseById.get(String(ccx.course_id))??{};const o:AnyRow=outcomeById.get(String(x.plo_id))??{};const row:AnyRow={...x,course_code:c.course_code??null,title_th:c.title_th??null,plo_code:o.canonical_code??null};return row;}) as AnyRow[]).sort((a,b)=>String(a.plo_code).localeCompare(String(b.plo_code))||String(a.course_code).localeCompare(String(b.course_code)));
 return {state:'READY' as const,userId:userData.user.id,programme,version,summary:sumR.data,courses:courseList,groups:groupRows,studyPlan:studyList,mappings:mappingList,provenance:(provR.data??[]) as AnyRow[]};
}
