import { notFound } from 'next/navigation';

type Module = {title:string;description:string;status:string;items:{title:string;body:string}[]};
const moduleData:Record<string,Module>= {
programme:{title:'Programme Overview',description:'Controlled programme identity, curriculum version and pilot readiness.',status:'NON-PRODUCTION · CONTROLLED VALIDATION',items:[{title:'Programme identity',body:'B.Ed. Health Education and Physical Education · Programme code 25510071103503'},{title:'Curriculum version',body:'2567-SOURCEB-VALIDATION · DRAFT · VALIDATION_ONLY · NOT ACTIVE · NOT PUBLISHED'},{title:'Verified structure',body:'151 credits · 92 courses · 16 course groups · 54 study-plan rows · 7 PLOs'},{title:'I-R-M coverage',body:'99 approved Course→PLO pairs · 78 mapped courses · I 9 · R 72 · M 18'}]},
curriculum:{title:'Curriculum Structure',description:'Read-only controlled curriculum structure and Source-B validation registry.',status:'READ-ONLY · SOURCE-BOUND',items:[{title:'Controlled registry',body:'92 verified courses with lossless credit-pattern binding; no fabricated course identities.'},{title:'Course groups',body:'16 controlled groups. Group labels and memberships must come from Source-B only.'},{title:'Curriculum state',body:'DRAFT / VALIDATION_ONLY. Canonical activation and publication have not been attempted.'},{title:'Import Studio',body:'Open the authority-aware Source-B validation workspace for provenance and staged-import status.'}]},
'study-plan':{title:'Study Plan',description:'Controlled year/semester planning with choice semantics preserved.',status:'54 LOGICAL ROWS · 151 CREDITS',items:[{title:'Reconciliation',body:'54 logical study-plan rows reconcile to 151 credits.'},{title:'Choice semantics',body:'Choice pools remain choice pools; no placeholder is converted into a fabricated course.'},{title:'Academic effective period',body:'ภาคการศึกษาที่ 2 ปีการศึกษา 2567. No invented calendar date.'},{title:'Read-only boundary',body:'Pilot presentation only. No canonical write or activation control is exposed.'}]},
traceability:{title:'PLO / Course Traceability',description:'Outcome-to-course relationships from the approved controlled I-R-M binding.',status:'99 VERIFIED RELATIONSHIPS',items:[{title:'PLO registry',body:'7 PLOs are represented in the controlled Source-B validation version.'},{title:'Mapped courses',body:'78 of 92 courses participate in the approved Course→PLO I-R-M binding.'},{title:'Unmapped courses',body:'14 courses are outside the approved I-R-M mapping; no relationship is inferred.'},{title:'Relationship provenance',body:'Course→PLO relationship follows curriculum source; I/R/M level follows the approved I-R-M source.'}]},
mapping:{title:'PLO × Course / I-R-M',description:'Inspect approved Introduce–Reinforce–Master relationships without inferred links.',status:'I 9 · R 72 · M 18',items:[{title:'Introduce',body:'9 approved I relationships.'},{title:'Reinforce',body:'72 approved R relationships.'},{title:'Master',body:'18 approved M relationships.'},{title:'Total',body:'99 approved Course→PLO relationships across 78 mapped courses.'}]},
evidence:{title:'Evidence Explorer',description:'Evidence-first registry semantics with provenance and admission firewall.',status:'EVIDENCE CANDIDATE ≠ ADMITTED EVIDENCE',items:[{title:'Source Document',body:'Controlled source identity and checksum may support provenance when verified.'},{title:'Extracted Candidate',body:'Parser/extractor output is not canonical data and is not Audit Evidence by itself.'},{title:'Validated Record',body:'Verified candidate/read-model state remains distinct from institutional activation.'},{title:'Audit Evidence',body:'Admission requires Evidence ID, type, source, version/date, authority/owner, assertion and verification status.'}]},
qa:{title:'QA / CPRR',description:'Read-only quality and curriculum review surface; no fabricated readiness score.',status:'INSUFFICIENT VERIFIED EVIDENCE FOR QA PASS/FAIL',items:[{title:'QA readiness',body:'No overall QA PASS/FAIL is asserted without a verified evidence set.'},{title:'CPRR',body:'Review state and findings may be shown only when controlled records are available.'},{title:'Evidence relationship',body:'Evidence candidate status must remain separate from admitted Audit Evidence.'},{title:'Human authority',body:'Formal findings and closure decisions remain human-governed.'}]},
reviews:{title:'Review Queue',description:'Authority-aware academic review work queue.',status:'HUMAN AUTHORITY PRESERVED',items:[{title:'Pending review',body:'Only controlled review records may be presented as pending.'},{title:'Decision readiness',body:'AI may summarize evidence but cannot approve or reject.'},{title:'Recusal / conflict',body:'Authority and conflict-of-interest checks remain backend-governed.'},{title:'Pilot boundary',body:'No approval action in this pilot may activate or publish the curriculum.'}]},
calendar:{title:'Academic Tasks',description:'Controlled academic milestones and pilot tasks.',status:'NO FABRICATED DEADLINES',items:[{title:'Academic milestones',body:'Display only dates present in controlled records.'},{title:'Programme tasks',body:'Operational tasks remain context unless backed by a controlled record.'},{title:'Upcoming gates',body:'Human Decision Gates are shown separately from technical readiness.'},{title:'Environment',body:'No Production schedule or deployment deadline is inferred.'}]},
audit:{title:'Provenance',description:'Trace source identity, version, authority and verification status.',status:'SOURCE-BOUND · EVIDENCE-FIRST',items:[{title:'Source-B checksum',body:'f580fec8bb661181cbc0dff3c58473563c4b723f2dde5e863d91667ea4ec3557'},{title:'Programme',body:'25510071103503 · version 2567-SOURCEB-VALIDATION'},{title:'Admission firewall',body:'Conversation and AI summaries are not Audit Evidence by default.'},{title:'Conflict handling',body:'Verified evidence / controlled baseline overrides discussion; conflicts require reconciliation.'}]},
ai:{title:'AI Advisory',description:'Advisory-only academic assistance with explicit human-decision boundary.',status:'AI ADVISORY · HUMAN DECISION REQUIRED',items:[{title:'Permitted',body:'Analyze · Summarize · Compare · Explain · Flag gaps · Recommend · Draft'},{title:'Prohibited',body:'Approve · Activate · Publish · Grant/Revoke authority · Change I-R-M · Admit Audit Evidence'},{title:'Evidence boundary',body:'AI output remains advisory origin unless separately verified and admitted.'},{title:'Failure mode',body:'AI or connector unavailability must not stop the core academic workflow.'}]},
governance:{title:'Settings / Governance',description:'Controlled pilot gate posture and environment firewall.',status:'HEPE-PILOT-03 · NON-PRODUCTION',items:[{title:'Environment',body:'NON-PRODUCTION only. Preview deployment does not imply Production authorization.'},{title:'Curriculum state',body:'DRAFT · VALIDATION_ONLY · NOT ACTIVE · NOT PUBLISHED.'},{title:'Human decision gates',body:'Canonical activation, publication, PR merge and Production require separate explicit authorization.'},{title:'Audit evidence',body:'Automated test output remains EVIDENCE CANDIDATE until formally admitted.'}]}
};

export function generateStaticParams(){return Object.keys(moduleData).map(module=>({module}))}
export default async function ModulePage({params}:{params:Promise<{module:string}>}){
 const {module}=await params;const data=moduleData[module];if(!data)notFound();
 return <main className="workspace"><div className="module-wrap"><a className="breadcrumb" href="/">← Academic Command Center</a><section className="hero"><div className="brand-kicker">HEPE · BED-HEPE · CONTROLLED PILOT · NON-PRODUCTION</div><h1>{data.title}</h1><p>{data.description}</p></section><div className="pill">{data.status}</div>{module==='curriculum'&&<section className="card item-card"><div className="label">Controlled validation</div><h2>Curriculum Import / Registry</h2><p>Authority-aware Source-B validation workspace. Validation data is not active or published.</p><a className="breadcrumb" href="/curriculum-import">Open Curriculum Import Studio →</a></section>}<div className="grid g2">{data.items.map(item=><article className="card item-card" key={item.title}><div className="label">Controlled pilot workspace</div><h2>{item.title}</h2><p>{item.body}</p></article>)}</div><div className="firewall">Environment firewall · NON-PRODUCTION only · NOT ACTIVE · NOT PUBLISHED · Human academic authority preserved.</div><footer className="footer-note">Evidence-first · Source-bound · No fabrication · No automatic Audit Evidence admission.</footer></div></main>
}
