import { loadPilotReadModel } from '../../lib/hepe/pilot-read';

export default async function StudyPlanPage({searchParams}:{searchParams:Promise<{year?:string}>}){
 const model=await loadPilotReadModel(); const sp=await searchParams;
 if(model.state!=='READY') return <main className="workspace"><div className="module-wrap"><a className="breadcrumb" href="/">← Academic Command Center</a><section className="hero"><div className="brand-kicker">HEPE · CONTROLLED PILOT · NON-PRODUCTION</div><h1>Study Plan</h1><p>Authority-aware controlled study-plan read experience.</p></section><div className="pill">{model.state}</div></div></main>;
 const year=sp.year?Number(sp.year):0; const rows=model.studyPlan.filter((x:any)=>!year||Number(x.academic_year_no)===year);
 const years=[...new Set(model.studyPlan.map((x:any)=>Number(x.academic_year_no)))].sort();
 const subtotal=(list:any[])=>list.reduce((s,x)=>s+Number(x.required_credits??0),0);
 return <main className="workspace"><div className="module-wrap"><a className="breadcrumb" href="/">← Academic Command Center</a><section className="hero"><div className="brand-kicker">HEPE · BED-HEPE · NON-PRODUCTION</div><h1>Study Plan</h1><p>54 logical rows totaling 151 credits. Choice-pool semantics are preserved and never converted into fabricated course identities.</p></section><div className="pill">54 LOGICAL ROWS · 151 CREDITS · READ ONLY</div>
 <form className="filterbar" method="get"><label>Academic year <select name="year" defaultValue={sp.year??''}><option value="">All years</option>{years.map(y=><option key={y} value={y}>Year {y}</option>)}</select></label><button type="submit">Apply</button></form>
 {years.filter(y=>!year||y===year).map(y=><section key={y} className="card" style={{marginBottom:14}}><h2 className="section-title">Year {y}</h2>{[...new Set(rows.filter((r:any)=>Number(r.academic_year_no)===y).map((r:any)=>String(r.term_code)))].map(term=>{const termRows=rows.filter((r:any)=>Number(r.academic_year_no)===y&&String(r.term_code)===term);return <div key={term} style={{marginBottom:18}}><h3>Semester {term} · {subtotal(termRows)} credits</h3><div className="table-wrap"><table><thead><tr><th>#</th><th>Kind</th><th>Course / choice</th><th>Credits</th><th>Source / verification</th></tr></thead><tbody>{termRows.map((r:any)=><tr key={r.study_plan_entry_id}><td>{r.sequence_no}</td><td>{r.entry_kind}</td><td>{r.course_code?<><strong>{r.course_code}</strong><br/>{r.title_th||''}</>:<><strong>CHOICE / GROUP</strong><br/>{r.raw_entry_text||r.group_name_th||'NOT PROVIDED'}</>}</td><td>{String(r.required_credits??0)}</td><td>{r.source_page?`p.${r.source_page}`:'PROVENANCE NOT AVAILABLE'}<br/><span className="note">{r.verification_status??'UNVERIFIED'}</span></td></tr>)}</tbody></table></div></div>})}</section>)}
 <div className="firewall">Displayed rows: {rows.length} · Displayed credits: {subtotal(rows)} · Programme total remains 151 credits · No fake course identity.</div></div></main>
}
