import { demoTickets, supportBoundary } from './support-model';

export default function SupportHome(){
  const open=demoTickets.filter(t=>!['CLOSED','RESOLVED'].includes(t.support_status)).length;
  const resolved=demoTickets.filter(t=>t.support_status==='RESOLVED').length;
  return <main className="support-shell">
    <header className="support-top"><div><div className="eyebrow">HEPE SUPPORT CENTER</div><h1>ศูนย์ช่วยเหลือและติดตามปัญหา</h1><p>พื้นที่รับแจ้งปัญหา ติดตามการแก้ไข และเชื่อมโยง traceability โดยไม่เปลี่ยนข้อมูลหลักสูตรหรืออำนาจทางวิชาการโดยตรง</p></div><div className="support-badges"><span className="support-badge">CONTROLLED PILOT</span><span className="support-badge">NON-PRODUCTION</span></div></header>
    <div className="support-notice"><strong>Governance firewall:</strong> Ticket ≠ Finding ≠ Evidence ≠ Approval ≠ Canonical Change · Audit Evidence Admission = NOT ADMITTED</div>
    <section className="support-grid support-grid-4"><article className="support-card support-kpi"><span>Open / Active</span><strong>{open}</strong><small>synthetic demo only</small></article><article className="support-card support-kpi"><span>Resolved</span><strong>{resolved}</strong><small>synthetic demo only</small></article><article className="support-card support-kpi"><span>Production</span><strong>NO</strong><small>boundary locked</small></article><article className="support-card support-kpi"><span>Audit admission</span><strong>NO</strong><small>separate gate required</small></article></section>
    <section className="support-grid support-grid-3" style={{marginTop:16}}><a className="support-card support-action" href="/support/new"><div><strong>เปิด Ticket ใหม่</strong><p>บันทึก issue พร้อม context แบบไม่เก็บ secret</p></div></a><a className="support-card support-action" href="/support/triage"><div><strong>Triage Queue</strong><p>คัดแยก severity / category / assignment</p></div></a><a className="support-card support-action" href="/support/analytics"><div><strong>Support Analytics</strong><p>ดูข้อมูลที่มีจริงเท่านั้น ไม่สร้างตัวเลขสมมติ</p></div></a></section>
    <section className="support-grid support-grid-2" style={{marginTop:16}}><article className="support-card"><h2>My Tickets</h2><div className="support-list">{demoTickets.map(t=><a className="support-row" key={t.ticket_id} href={`/support/ticket/${t.ticket_id}`}><div><strong>{t.ticket_number} · {t.title}</strong><div className="support-muted">{t.ticket_category} · {t.course_code||t.module_code}</div></div><span className="support-status">{t.support_status}</span></a>)}</div></article><article className="support-card"><h2>Support Health</h2><div className="support-list"><div className="support-row"><span>Canonical mutation</span><strong className="support-good">BLOCKED</strong></div><div className="support-row"><span>AI final decision</span><strong className="support-good">BLOCKED</strong></div><div className="support-row"><span>Real email send</span><strong className="support-good">BLOCKED</strong></div><div className="support-row"><span>Attachment persistence</span><strong>{supportBoundary.attachmentPersistence?'ON':'NOT CONNECTED'}</strong></div></div></article></section>
    <section className="support-grid support-grid-2" style={{marginTop:16}}><a className="support-card support-action" href="/support/known-issues"><div><strong>Known Issues / Resolution Knowledge</strong><p>เฉพาะ candidate knowledge ที่ผ่าน human review ในอนาคต</p></div></a><article className="support-card support-ai"><span className="support-status">AI ADVISORY ONLY</span><h3 style={{marginTop:8}}>AI Support Advisor</h3><p>เสนอ category, severity, troubleshooting, duplicate/recurring issue candidates ได้ แต่ห้าม close ticket, grant authority, modify canonical data หรือ admit evidence.</p></article></section>
    <footer className="support-footer">HEPE-SUPPORT-01 · local/synthetic controlled pilot · no database support schema in this gate</footer>
  </main>
}
