"use client";
import {useMemo,useState} from "react";
import {assess,defaultRule,PANYA_PERSON,PANYA_PUBLICATIONS,type WindowMode} from "../lib/publications/panya-fixture";
const statusText={COUNTABLE:"นับได้ตามกฎที่ยืนยัน",OUTSIDE_WINDOW:"ไม่นับ: นอกช่วงเวลา",NEEDS_POLICY_REVIEW:"รอตรวจเกณฑ์/หลักฐาน",NEEDS_EVIDENCE:"ข้อมูลวัน/หลักฐานไม่ครบ"};
const colors={COUNTABLE:"#027a48",OUTSIDE_WINDOW:"#667085",NEEDS_POLICY_REVIEW:"#b54708",NEEDS_EVIDENCE:"#b42318"};
export default function FacultyPublications(){
 const [year,setYear]=useState(2569),[mode,setMode]=useState<WindowMode>("CALENDAR");
 const results=useMemo(()=>PANYA_PUBLICATIONS.map(p=>({p,result:assess(p,year,mode,false)})),[year,mode]);
 const inWindow=results.filter(x=>x.result.status!=="OUTSIDE_WINDOW").length;
 const counted=results.filter(x=>x.result.status==="COUNTABLE").length;
 const pending=results.filter(x=>x.result.status==="NEEDS_POLICY_REVIEW"||x.result.status==="NEEDS_EVIDENCE").length;
 const yearRows=Array.from({length:5},(_,i)=>year-4+i).map((y,index)=>{
   const works=PANYA_PUBLICATIONS.filter(p=>p.yearBE===y);
   const yearResults=works.map(p=>({p,result:assess(p,year,mode,false)}));
   return {y,index:index+1,works,total:works.length,
     eligible:yearResults.filter(x=>x.result.status==="COUNTABLE").length,
     pending:yearResults.filter(x=>x.result.status==="NEEDS_POLICY_REVIEW"||x.result.status==="NEEDS_EVIDENCE").length,
     out:yearResults.filter(x=>x.result.status==="OUTSIDE_WINDOW").length};
 });
 const allYears=Array.from({length:7},(_,i)=>year-6+i);
 const historyRows=allYears.map((end)=>{const start=end-4;const w=PANYA_PUBLICATIONS.filter(p=>p.yearBE>=start&&p.yearBE<=end);return {end,start,works:w.length,verified:0,pending:w.length};});
 const verdict=counted>=defaultRule.minimum?"ผ่านเกณฑ์ผลงานตามข้อมูลที่รับรอง":"รอยืนยัน — ยังสรุปผ่าน/ไม่ผ่านไม่ได้";
 return <main style={{maxWidth:1250,margin:"0 auto",padding:"24px 18px",fontFamily:"system-ui,sans-serif",color:"#192a42"}}>
 <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,flexWrap:"wrap"}}><a href="/quality">← รายงานคุณภาพ</a><span style={{borderRadius:30,background:"#fff1d6",padding:"7px 12px",fontSize:12,fontWeight:700}}>NON-PRODUCTION · DEMONSTRATION</span></div>
 <section style={{marginTop:14,padding:16,background:"#e9f5ef",borderRadius:12}}><b>หลักสูตรปรับปรุง พ.ศ. 2570</b><p>ประเมินย้อนหลังโดยใช้วันที่สภามหาวิทยาลัยอนุมัติจริง ไม่ใช้ปี 2570 เป็นวันอ้างอิงแทน</p><a href="/faculty-publications/2570" style={{display:"inline-block",background:"#1677ff",color:"white",borderRadius:9,padding:"10px 16px",textDecoration:"none",fontWeight:700}}>เปิดตัวเลือกหลักสูตรปรับปรุง 2570 →</a></section><section style={{marginTop:18,padding:24,background:"#eff6ff",borderRadius:18}}><h1 style={{margin:"0 0 8px"}}>ระบบนับผลงานทางวิชาการย้อนหลัง</h1><p>ทะเบียนผลงาน · รอบห้าปี · เกณฑ์ตามระดับหลักสูตร · หลักฐานก่อนการรับรอง</p><h2 style={{marginBottom:4}}>{PANYA_PERSON.name}</h2><p style={{marginTop:0,fontSize:13}}>Person ID: {PANYA_PERSON.id} · ยืนยันตัวบุคคลจากทะเบียน Supabase · ข้อมูลผลงานเป็นชุดตัวอย่างจากเอกสารและแหล่งเผยแพร่ ไม่ใช่ทะเบียนผลงานที่ผ่านการรับรองใน Supabase</p></section>
 <section style={{display:"flex",alignItems:"end",gap:12,flexWrap:"wrap",margin:"18px 0"}}>
 <label>ปีอ้างอิง<br/><select aria-label="ปีอ้างอิง" value={year} onChange={e=>setYear(Number(e.target.value))} style={{padding:10,borderRadius:8}}>{[2569,2568,2567,2566,2565,2564,2563].map(y=><option value={y} key={y}>{y}</option>)}</select></label>
 <label>ประเภทรอบ<br/><select aria-label="ประเภทรอบ" value={mode} onChange={e=>setMode(e.target.value as WindowMode)} style={{padding:10,borderRadius:8}}><option value="CALENDAR">ปีปฏิทิน (จัดกลุ่มตามปีเผยแพร่)</option><option value="ACADEMIC">ปีการศึกษา (ตัวอย่างจัดกลุ่มตามปี พ.ศ.)</option><option value="FISCAL">ปีงบประมาณ (1 ต.ค.–30 ก.ย.)</option></select></label>
 <div style={{padding:10,background:"#f2f4f7",borderRadius:8}}>ช่วงที่เลือก: {year-4}–{year} · ปีอ้างอิงของหลักสูตรต้องยืนยันก่อนใช้ทางการ</div>
 </section>
 <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(170px,1fr))",gap:12}}>
 {[["รายการผลงานที่พบ",PANYA_PUBLICATIONS.length],["อยู่ในช่วง/รอตรวจ",inWindow],["ยืนยันนับได้",counted],["รอตรวจเพิ่มเติม",pending]].map(([a,b])=><div key={a} style={{padding:18,border:"1px solid #dde5ef",borderRadius:14,background:"white"}}><div style={{fontSize:13,color:"#667085"}}>{a}</div><strong style={{fontSize:28}}>{b}</strong></div>)}</section>
 <section style={{marginTop:16,padding:18,border:"1px solid #efce94",background:"#fffaeb",borderRadius:12}}><strong>ผลตรวจด้านผลงาน: {verdict}</strong><p style={{marginBottom:0}}>เกณฑ์สาธิตสำหรับหลักสูตรปริญญาตรีทางวิชาการ พ.ศ. 2565: อย่างน้อย 1 เรื่องในรอบ 5 ปี (ข้อ 10.1.1) ระบบต้องตรวจประเภทผลงาน ฉบับเต็ม วันเผยแพร่ และข้อกำหนดที่ใช้กับหลักสูตรก่อนให้ผลผ่าน/ไม่ผ่านอย่างเป็นทางการ; ยังไม่ประเมินคุณวุฒิและองค์ประกอบอื่น</p></section>
 <section style={{marginTop:18,padding:18,border:"1px solid #dde5ef",borderRadius:12}}>
 <h2 style={{marginTop:0}}>ตารางนับย้อนหลังแยกรายปีอย่างละเอียด</h2>
 <p>ปีอ้างอิง {year} นับรวมปีอ้างอิงเป็นปีที่ 5 และนับย้อนกลับ 4 ปีเต็มตามการจัดกลุ่มปีปฏิทิน: {year-4}, {year-3}, {year-2}, {year-1}, {year} (รวม 5 ปี ไม่ใช่ 6 ปี)</p>
 <div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:14}}><thead><tr style={{background:"#e8f1ff",textAlign:"left"}}>{["ลำดับปี","ปี พ.ศ. / ค.ศ.","ผลงานในทะเบียนตัวอย่าง","ผลงานที่รับรองนับได้","รายการรอตรวจ","รายละเอียดหลักฐาน"].map(h=><th key={h} style={{padding:11,borderBottom:"1px solid #cdd8e8"}}>{h}</th>)}</tr></thead>
 <tbody>{yearRows.map(r=><tr key={r.y}><td style={{padding:11,borderBottom:"1px solid #e5e9f0"}}>ปีที่ {r.index}</td><td style={{padding:11,borderBottom:"1px solid #e5e9f0"}}><b>{r.y}</b> / {r.y-543}</td><td style={{padding:11,borderBottom:"1px solid #e5e9f0"}}>{r.total} รายการ</td><td style={{padding:11,borderBottom:"1px solid #e5e9f0"}}>{r.eligible}</td><td style={{padding:11,borderBottom:"1px solid #e5e9f0"}}>{r.pending}</td><td style={{padding:11,borderBottom:"1px solid #e5e9f0"}}>{r.works.length?r.works.map(p=><div key={p.id}>{p.title} <small>({p.evidence})</small></div>):<span style={{color:"#667085"}}>ยังไม่พบในทะเบียนตัวอย่าง — ไม่ใช่ข้อยืนยันว่าไม่มีผลงาน</span>}</td></tr>)}
 <tr style={{background:"#eff6ff",fontWeight:700}}><td colSpan={2} style={{padding:11}}>รวม 5 ปี</td><td style={{padding:11}}>{yearRows.reduce((a,r)=>a+r.total,0)}</td><td style={{padding:11}}>{yearRows.reduce((a,r)=>a+r.eligible,0)}</td><td style={{padding:11}}>{yearRows.reduce((a,r)=>a+r.pending,0)}</td><td style={{padding:11}}>รายการซ้ำข้ามฐานข้อมูลต้องรวมเป็นผลงานเดียว</td></tr></tbody></table></div>
 <p style={{color:"#667085",fontSize:13}}>เมื่อเลือกรอบปีงบประมาณ ต้องใช้วันที่เผยแพร่หรือหนังสือตอบรับ Full paper เพื่อตัดสินผลงานบริเวณวันต้นรอบและปลายรอบ; ตารางนี้แสดงจำนวนตามปี พ.ศ. ที่บันทึกไว้ก่อน และไม่ใช่ผลรับรองปีงบประมาณหรือปีการศึกษาโดยอัตโนมัติ</p>
 </section>
 <section style={{marginTop:18,padding:18,border:"1px solid #dde5ef",borderRadius:12}}>
 <h2 style={{marginTop:0}}>ตารางเลื่อนรอบย้อนหลัง (Rolling 5-year history)</h2>
 <p>แต่ละแถวเป็นหน้าต่างเวลา 5 ปีของตัวเอง ไม่ควรนำยอดรวมทุกแถวไปบวกกัน เพราะผลงานเรื่องเดียวอาจอยู่ในหลายรอบได้</p>
 <div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:14}}><thead><tr style={{background:"#e8f1ff",textAlign:"left"}}>{["ปีประเมิน","ช่วง 5 ปี (รวมปีประเมิน)","จำนวนผลงานที่พบ","รับรองนับได้","รอตรวจ","ผลด้านข้อมูล"].map(h=><th key={h} style={{padding:10}}>{h}</th>)}</tr></thead><tbody>{historyRows.map(r=><tr key={r.end} style={{background:r.end===year?"#f0f7ff":"white"}}><td style={{padding:10}}>{r.end}</td><td style={{padding:10}}>{r.start}–{r.end}</td><td style={{padding:10}}>{r.works}</td><td style={{padding:10}}>{r.verified}</td><td style={{padding:10}}>{r.pending}</td><td style={{padding:10}}>ยังไม่ยืนยันผลตามเกณฑ์</td></tr>)}</tbody></table></div>
 <p style={{color:"#667085",fontSize:13}}>ตารางเลื่อนรอบเป็นตัวอย่างการนับด้วยปีปฏิทินเท่านั้น การรับรองอย่างเป็นทางการใช้วันที่อ้างอิงและ Rule Set ของหลักสูตรที่ตรวจสอบแล้ว</p>
 </section>
 <div style={{overflowX:"auto",marginTop:18}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:14}}><thead><tr style={{background:"#e8f1ff",textAlign:"left"}}>{["ปี พ.ศ.","ชื่อผลงาน / แหล่งเผยแพร่","ประเภท","หลักฐาน","ผลตรวจตามรอบ","รายการที่ต้องทำ"].map(h=><th key={h} style={{padding:12,borderBottom:"1px solid #ccd8e8"}}>{h}</th>)}</tr></thead><tbody>{results.map(({p,result})=><tr key={p.id}><td style={{padding:12,borderBottom:"1px solid #e5e9f0",verticalAlign:"top"}}>{p.yearBE}</td><td style={{padding:12,borderBottom:"1px solid #e5e9f0",minWidth:300,verticalAlign:"top"}}><b>{p.title}</b><p style={{margin:"6px 0",fontSize:12}}>{p.citation}</p><small>{p.source}</small>{p.url?<p><a href={p.url} target="_blank" rel="noreferrer">หลักฐาน DOI ↗</a></p>:null}</td><td style={{padding:12,borderBottom:"1px solid #e5e9f0",verticalAlign:"top"}}>{p.kind}</td><td style={{padding:12,borderBottom:"1px solid #e5e9f0",verticalAlign:"top"}}>{p.evidence}</td><td style={{padding:12,borderBottom:"1px solid #e5e9f0",minWidth:150,verticalAlign:"top"}}><strong style={{color:colors[result.status]}}>{statusText[result.status]}</strong><p style={{fontSize:12}}>{result.reason}</p></td><td style={{padding:12,borderBottom:"1px solid #e5e9f0",verticalAlign:"top"}}>{p.notes}</td></tr>)}</tbody></table></div>
 <section style={{marginTop:18,padding:18,border:"1px solid #dde5ef",borderRadius:12}}><h3>เกณฑ์และการควบคุมข้อมูล</h3><p>อ้างอิง: <a href="https://www.ops.go.th/th/role/edu-standard/item/6942-2022-07-22-03-17-22">เกณฑ์มาตรฐานหลักสูตรระดับปริญญาตรี พ.ศ. 2565</a> และ <a href="https://www.ops.go.th/th/ches-resolutions/meeting-important/item/5669-6">แนวปฏิบัติการพิจารณาผลงานและวันที่เผยแพร่</a> โปรดตรวจแนวทางใหม่เกี่ยวกับ Proceedings และการบังคับใช้กับรุ่นหลักสูตรที่เกี่ยวข้อง</p><p>ปีการศึกษาในหน้านี้เป็นเพียงการจัดกลุ่มด้วยปี พ.ศ. ยังไม่ได้เทียบวันเริ่ม–สิ้นสุดของมหาวิทยาลัย; รอบปีงบประมาณที่ไม่พบวันเผยแพร่จะไม่ตัดสินให้นับโดยประมาณ; ผลงานเรื่องเดียวไม่นับซ้ำเมื่อปรากฏหลายฐานข้อมูล</p><p style={{fontWeight:700,color:"#b42318"}}>ไม่มีการแก้ฐานข้อมูล ไม่มีการยืนยันผลงานแทนผู้ตรวจ และไม่มีการให้สถานะคุณสมบัติบุคคลอย่างเป็นทางการ</p></section>
 </main>;
}
