export type HepeTourStep={id:string;title:string;body:string;selector?:string};
export type HepeHelpArticle={slug:string;title:string;summary:string;sections:{heading:string;body:string}[]};
export type HepeHelpBinding={route:string;slug:string;tourId:string;steps:HepeTourStep[]};

export const helpArticles:Record<string,HepeHelpArticle>={
 'my-workspace':{slug:'my-workspace',title:'My Academic Workspace',summary:'จุดเริ่มต้นสำหรับงานสอนประจำวัน โดย Governance และ Traceability ทำงานเชื่อมโยงอยู่ด้านหลัง',sections:[{heading:'เริ่มจากตรงไหน',body:'ตรวจ Academic Year และป้าย NON-PRODUCTION ก่อน จากนั้นเริ่มที่ My Courses หรือ Quick Entry ตามงานที่ต้องทำ'},{heading:'ขอบเขต',body:'Controlled Pilot นี้ใช้ SYNTHETIC / TEST DATA ONLY และไม่ถือเป็น Production Authorization'}]},
 'my-courses':{slug:'my-courses',title:'My Courses',summary:'ดูรายวิชาที่ผู้ใช้มีสิทธิ์เห็นผ่าน authenticated RLS scope',sections:[{heading:'Runtime State',body:'VERIFIED, EMPTY, AUTH_REQUIRED, QUERY_ERROR และ RUNTIME_NOT_CONFIGURED เป็นสถานะการเข้าถึง ไม่ใช่คะแนนคุณภาพรายวิชา'},{heading:'เมื่อไม่พบรายวิชา',body:'EMPTY ไม่ได้แปลว่าข้อมูลถูกลบ และ AUTH_REQUIRED ไม่ได้แปลว่าระบบเสีย'}]},
 'course-workspace':{slug:'course-workspace',title:'Course Workspace',summary:'ศูนย์กลางสำหรับ Teaching, Assessment, Evidence และ Plan vs Actual ของรายวิชาเดียว',sections:[{heading:'ตรวจบริบท',body:'ตรวจ Course code, title, credit value และ runtime state ก่อนทำงานต่อ'},{heading:'ตัวเลขสรุป',body:'Learning Activities, Assessments และ Delivery Records เป็นข้อมูลเชิงบริบท ไม่ใช่ readiness score'}]},
 'quick-entry':{slug:'quick-entry',title:'Quick Entry',summary:'บันทึกงานหลังสอนและเพิ่มหลักฐานการประเมินโดยลดการกรอกข้อมูลซ้ำ',sections:[{heading:'บันทึกหลังสอน',body:'เลือกกิจกรรม ตรวจปี/ภาค ระบุวันที่สอน แล้วบันทึก'},{heading:'เพิ่มหลักฐาน',body:'เลือก Assessment ระบุชื่อหลักฐานและวันที่มีผล การเพิ่ม Evidence ไม่เท่ากับการรับเข้า Audit Evidence Set โดยอัตโนมัติ'}]},
 'learning-teaching':{slug:'learning-teaching',title:'Learning & Teaching',summary:'ตรวจ Learning Activity, CLO/Assessment links และ Delivery Evidence',sections:[{heading:'NO VERIFIED DATA',body:'หมายถึงยังไม่มีข้อมูลที่ระบบยืนยันได้สำหรับ field นั้น'},{heading:'NO EVIDENCE',body:'หมายถึงยังไม่พบหลักฐานใน read model ปัจจุบัน ไม่ควรตีความเป็น FAIL โดยอัตโนมัติ'}]},
 'assessment':{slug:'assessment',title:'Assessment',summary:'ดู Assessment versions และ outcome alignment ภายใต้ RLS scope',sections:[{heading:'Linked Outcomes',body:'จำนวนความสัมพันธ์กับ Outcomes ไม่ใช่คะแนนคุณภาพ ความครบถ้วน หรือ compliance'},{heading:'Approval',body:'Approved At เป็นสถานะของ version นั้น ไม่ใช่ Production Authorization'}]},
 'evidence':{slug:'evidence',title:'Evidence',summary:'ตรวจ Evidence identity, verification, sufficiency และ provenance gaps',sections:[{heading:'Evidence Admission',body:'Uploaded หรือ Registered Evidence ไม่เป็น Audit Evidence โดยอัตโนมัติ ต้องตรวจ Source, Version/Date, Authority/Owner, Relevant Assertion และ Verification Status'},{heading:'NOT_YET_VERIFIED',body:'ใช้เมื่อมี claim หรือข้อมูลอยู่ แต่ provenance/verification ที่จำเป็นยังไม่ครบ'}]},
 'plan-actual':{slug:'plan-actual',title:'Plan vs Actual',summary:'เปรียบเทียบแผนกับ Delivery Evidence, CLO links และ Assessment links',sections:[{heading:'NO EVIDENCE',body:'ยังไม่มี Delivery Evidence ใน read model ปัจจุบัน'},{heading:'PARTIALLY ALIGNED',body:'ยังไม่มีหลักฐานเพียงพอให้ประกาศ ALIGNED อย่างสมบูรณ์ Human review ยังคง authoritative'}]},
 'traceability':{slug:'traceability',title:'PLO / CLO Traceability',summary:'ติดตามความสัมพันธ์จาก Programme → Course → CLO → PLO โดยใช้ controlled mapping',sections:[{heading:'Controlled Mapping',body:'HEPE ไม่สร้าง relationship ที่ไม่มีอยู่ใน controlled source'},{heading:'การอ่านเส้นทาง',body:'สำหรับการสอนสามารถอ่าน CLO → Learning Activity → Assessment → Evidence เพื่อย้อนกลับแหล่งข้อมูล'}]},
 'troubleshooting':{slug:'troubleshooting',title:'Troubleshooting',summary:'ความหมายและแนวทางรับมือ Runtime State ที่พบบ่อย',sections:[{heading:'AUTH_REQUIRED',body:'ต้องเข้าสู่ระบบด้วย HEPE session ที่ได้รับสิทธิ์'},{heading:'EMPTY',body:'ไม่มีข้อมูลที่มองเห็นได้ภายใต้ authority scope ปัจจุบัน'},{heading:'QUERY_ERROR',body:'controlled source อ่านไม่ได้ใน session/RLS ปัจจุบัน'},{heading:'RUNTIME_NOT_CONFIGURED',body:'Preview deployment ยังไม่มี runtime binding ที่พร้อมใช้งาน'}]}
};

const bindings:HepeHelpBinding[]=[
 {route:'/',slug:'my-workspace',tourId:'GT-02',steps:[{id:'GT-02-1',title:'My Academic Workspace',body:'เริ่มงานสอนจากพื้นที่นี้ โดย Governance ทำงานอยู่ด้านหลัง',selector:'[data-tour="workspace-hero"]'},{id:'GT-02-2',title:'My Courses',body:'เปิดรายวิชาที่คุณมองเห็นตามสิทธิ์',selector:'[data-tour="my-courses"]'},{id:'GT-02-3',title:'Quick Entry',body:'บันทึกหลังสอนหรือเพิ่มหลักฐานจากงานประจำวัน',selector:'[data-tour="quick-entry"]'}]},
 {route:'/my-courses',slug:'my-courses',tourId:'GT-03',steps:[{id:'GT-03-1',title:'รายวิชาของฉัน',body:'รายการนี้ถูกจำกัดตาม authenticated RLS scope',selector:'[data-tour="courses-state"]'},{id:'GT-03-2',title:'เปิด Course Workspace',body:'เลือกรายวิชาเพื่อรักษา course context ระหว่าง workflow',selector:'[data-tour="course-list"]'}]},
 {route:'/course-workspace/',slug:'course-workspace',tourId:'GT-04',steps:[{id:'GT-04-1',title:'Course Workspace',body:'ตรวจชื่อรายวิชาและ runtime state ก่อนเริ่ม',selector:'[data-tour="course-hero"]'},{id:'GT-04-2',title:'ทำงานรายวิชานี้ต่อ',body:'ไป Quick Entry, Teaching, Assessment, Plan vs Actual หรือ Evidence',selector:'[data-tour="course-actions"]'}]},
 {route:'/pilot-entry',slug:'quick-entry',tourId:'GT-06',steps:[{id:'GT-06-1',title:'Quick Entry',body:'บันทึกงานประจำวันโดยลดการกรอกข้อมูลซ้ำ',selector:'[data-tour="quick-entry-hero"]'},{id:'GT-06-2',title:'บันทึกหลังสอน',body:'เลือกกิจกรรม ตรวจปี/ภาค และยืนยันวันที่สอน',selector:'[data-tour="delivery-form"]'},{id:'GT-06-3',title:'เพิ่มหลักฐาน',body:'การเพิ่มหลักฐานยังไม่เท่ากับ Audit Evidence Admission',selector:'[data-tour="evidence-form"]'}]},
 {route:'/teaching',slug:'learning-teaching',tourId:'GT-05',steps:[{id:'GT-05-1',title:'Learning & Teaching',body:'อ่านกิจกรรม CLO/Assessment links และ Delivery Evidence',selector:'[data-tour="teaching-panel"]'}]},
 {route:'/assessment',slug:'assessment',tourId:'GT-07',steps:[{id:'GT-07-1',title:'Assessment',body:'Linked Outcomes เป็นข้อมูลความสัมพันธ์ ไม่ใช่ readiness score',selector:'[data-tour="assessment-panel"]'}]},
 {route:'/evidence',slug:'evidence',tourId:'GT-08',steps:[{id:'GT-08-1',title:'Evidence',body:'แยก verification, sufficiency และ provenance ออกจากกัน',selector:'[data-tour="module-live-panel"]'}]},
 {route:'/plan-actual',slug:'plan-actual',tourId:'GT-09',steps:[{id:'GT-09-1',title:'Plan vs Actual',body:'NO EVIDENCE ไม่เท่ากับ FAIL และ PARTIALLY ALIGNED ยังต้อง Human review',selector:'[data-tour="plan-panel"]'}]},
 {route:'/traceability',slug:'traceability',tourId:'GT-10',steps:[{id:'GT-10-1',title:'PLO / CLO Traceability',body:'ความสัมพันธ์ต้องมาจาก controlled mapping เท่านั้น',selector:'[data-tour="module-live-panel"]'}]}
];

export function getHelpBinding(pathname:string){
 return bindings.find(b=>b.route==='/'?pathname==='/':b.route.endsWith('/')?pathname.startsWith(b.route):pathname===b.route)??null;
}

export const helpIndex=Object.values(helpArticles);
